//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Document.java
//

#ifndef _OrgLukhnosLucenestudyDocument_H_
#define _OrgLukhnosLucenestudyDocument_H_

#include "J2ObjC_header.h"

@interface OrgLukhnosLucenestudyDocument : NSObject {
 @public
  NSString *title_;
  jint year_;
  jint rating_;
  jboolean positive_;
  NSString *review_;
  NSString *source_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)title
                         withInt:(jint)year
                         withInt:(jint)rating
                     withBoolean:(jboolean)positive
                    withNSString:(NSString *)review
                    withNSString:(NSString *)source;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudyDocument)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyDocument, title_, NSString *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyDocument, review_, NSString *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyDocument, source_, NSString *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(OrgLukhnosLucenestudyDocument *self, NSString *title, jint year, jint rating, jboolean positive, NSString *review, NSString *source);

FOUNDATION_EXPORT OrgLukhnosLucenestudyDocument *new_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(NSString *title, jint year, jint rating, jboolean positive, NSString *review, NSString *source) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyDocument)

#endif // _OrgLukhnosLucenestudyDocument_H_
