//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Document.java
//

#include "J2ObjC_source.h"
#include "java/lang/StringBuilder.h"
#include "org/lukhnos/lucenestudy/Document.h"

@implementation OrgLukhnosLucenestudyDocument

- (instancetype)initWithNSString:(NSString *)title
                         withInt:(jint)year
                         withInt:(jint)rating
                     withBoolean:(jboolean)positive
                    withNSString:(NSString *)review
                    withNSString:(NSString *)source {
  OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(self, title, year, rating, positive, review, source);
  return self;
}

- (NSString *)description {
  JavaLangStringBuilder *builder = new_JavaLangStringBuilder_init();
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([builder appendWithNSString:@"("])) appendWithNSString:title_])) appendWithNSString:@", "])) appendWithInt:year_])) appendWithNSString:@", "])) appendWithInt:rating_])) appendWithNSString:@", "])) appendWithBoolean:positive_])) appendWithNSString:@", "])) appendWithNSString:review_])) appendWithNSString:@", "])) appendWithNSString:source_])) appendWithNSString:@")"];
  return [builder description];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withInt:withInt:withBoolean:withNSString:withNSString:", "Document", NULL, 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "title_", NULL, 0x11, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "year_", NULL, 0x11, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "rating_", NULL, 0x11, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "positive_", NULL, 0x11, "Z", NULL, NULL, .constantValue.asLong = 0 },
    { "review_", NULL, 0x11, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "source_", NULL, 0x11, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudyDocument = { 2, "Document", "org.lukhnos.lucenestudy", NULL, 0x1, 2, methods, 6, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgLukhnosLucenestudyDocument;
}

@end

void OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(OrgLukhnosLucenestudyDocument *self, NSString *title, jint year, jint rating, jboolean positive, NSString *review, NSString *source) {
  (void) NSObject_init(self);
  self->title_ = title;
  self->year_ = year;
  self->rating_ = rating;
  self->positive_ = positive;
  self->review_ = review;
  self->source_ = source;
}

OrgLukhnosLucenestudyDocument *new_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(NSString *title, jint year, jint rating, jboolean positive, NSString *review, NSString *source) {
  OrgLukhnosLucenestudyDocument *self = [OrgLukhnosLucenestudyDocument alloc];
  OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(self, title, year, rating, positive, review, source);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudyDocument)
