//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Document.java
//

#include "J2ObjC_source.h"
#include "java/lang/StringBuilder.h"
#include "org/lukhnos/lucenestudy/Document.h"

#if !__has_feature(objc_arc)
#error "org/lukhnos/lucenestudy/Document must be compiled with ARC (-fobjc-arc)"
#endif

@implementation OrgLukhnosLucenestudyDocument

- (instancetype)initWithNSString:(NSString *)title
                         withInt:(jint)year
                         withInt:(jint)rating
                     withBoolean:(jboolean)positive
                    withNSString:(NSString *)review
                    withNSString:(NSString *)source {
  OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(self, title, year, rating, positive, review, source);
  return self;
}

- (NSString *)description {
  JavaLangStringBuilder *builder = new_JavaLangStringBuilder_init();
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([builder appendWithNSString:@"("])) appendWithNSString:title_])) appendWithNSString:@", "])) appendWithInt:year_])) appendWithNSString:@", "])) appendWithInt:rating_])) appendWithNSString:@", "])) appendWithBoolean:positive_])) appendWithNSString:@", "])) appendWithNSString:review_])) appendWithNSString:@", "])) appendWithNSString:source_])) appendWithNSString:@")"];
  return [builder description];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSString:withInt:withInt:withBoolean:withNSString:withNSString:);
  methods[1].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "title_", "LNSString;", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "year_", "I", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "rating_", "I", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "positive_", "Z", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "review_", "LNSString;", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "source_", "LNSString;", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;IIZLNSString;LNSString;", "toString" };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudyDocument = { "Document", "org.lukhnos.lucenestudy", ptrTable, methods, fields, 7, 0x1, 2, 6, -1, -1, -1, -1, -1 };
  return &_OrgLukhnosLucenestudyDocument;
}

@end

void OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(OrgLukhnosLucenestudyDocument *self, NSString *title, jint year, jint rating, jboolean positive, NSString *review, NSString *source) {
  NSObject_init(self);
  self->title_ = title;
  self->year_ = year;
  self->rating_ = rating;
  self->positive_ = positive;
  self->review_ = review;
  self->source_ = source;
}

OrgLukhnosLucenestudyDocument *new_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(NSString *title, jint year, jint rating, jboolean positive, NSString *review, NSString *source) {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudyDocument, initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_, title, year, rating, positive, review, source)
}

OrgLukhnosLucenestudyDocument *create_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(NSString *title, jint year, jint rating, jboolean positive, NSString *review, NSString *source) {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudyDocument, initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_, title, year, rating, positive, review, source)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudyDocument)
