//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/HighlightingHelper.java
//

#include "J2ObjC_source.h"
#include "java/io/IOException.h"
#include "java/lang/AssertionError.h"
#include "java/lang/Exception.h"
#include "java/util/regex/Matcher.h"
#include "java/util/regex/Pattern.h"
#include "org/apache/lucene/analysis/Analyzer.h"
#include "org/apache/lucene/search/Query.h"
#include "org/apache/lucene/search/highlight/Formatter.h"
#include "org/apache/lucene/search/highlight/Fragmenter.h"
#include "org/apache/lucene/search/highlight/Highlighter.h"
#include "org/apache/lucene/search/highlight/InvalidTokenOffsetsException.h"
#include "org/apache/lucene/search/highlight/QueryScorer.h"
#include "org/apache/lucene/search/highlight/SimpleHTMLFormatter.h"
#include "org/apache/lucene/search/highlight/SimpleSpanFragmenter.h"
#include "org/lukhnos/lucenestudy/HighlightingHelper.h"
#include "org/lukhnos/lucenestudy/MinimalHTMLEncoder.h"

#if !__has_feature(objc_arc)
#error "org/lukhnos/lucenestudy/HighlightingHelper must be compiled with ARC (-fobjc-arc)"
#endif

J2OBJC_INITIALIZED_DEFN(OrgLukhnosLucenestudyHighlightingHelper)

JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern;
JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern;

@implementation OrgLukhnosLucenestudyHighlightingHelper

- (instancetype)initPackagePrivateWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
                             withOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer {
  OrgLukhnosLucenestudyHighlightingHelper_initPackagePrivateWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(self, query, analyzer);
  return self;
}

- (jint)getFragmentLength {
  return fragmentLength_;
}

- (void)setFragmentLengthWithInt:(jint)length {
  if (length < 1) {
    @throw new_JavaLangAssertionError_initWithId_(@"length must be at least 1");
  }
  if (fragmentLength_ != length) {
    id<OrgApacheLuceneSearchHighlightFragmenter> fragmenter = new_OrgApacheLuceneSearchHighlightSimpleSpanFragmenter_initWithOrgApacheLuceneSearchHighlightQueryScorer_withInt_(scorer_, length);
    [((OrgApacheLuceneSearchHighlightHighlighter *) nil_chk(highlighter_)) setTextFragmenterWithOrgApacheLuceneSearchHighlightFragmenter:fragmenter];
    fragmentLength_ = length;
  }
}

- (void)setLineFeedHTMLEscapeWithBoolean:(jboolean)newLineToBr {
  [((OrgLukhnosLucenestudyMinimalHTMLEncoder *) nil_chk(encoder_)) setNewlineToBrWithBoolean:newLineToBr];
}

- (NSString *)highlightOrOriginalWithNSString:(NSString *)fieldName
                                 withNSString:(NSString *)text {
  if (text == nil) {
    return nil;
  }
  NSString *highlighted = [self highlightWithNSString:fieldName withNSString:text];
  if (highlighted != nil) {
    return highlighted;
  }
  jint cpCount = [text java_codePointCount:0 endIndex:[text java_length]];
  if (cpCount < fragmentLength_) {
    return text;
  }
  jint index = [text java_offsetByCodePoints:0 codePointOffset:fragmentLength_ - 1];
  return JreStrcat("$C", [text java_substring:0 endIndex:index], 0x2026);
}

- (NSString *)highlightWithNSString:(NSString *)fieldName
                       withNSString:(NSString *)text {
  if (text == nil) {
    return nil;
  }
  @try {
    NSString *highlighted = [((OrgApacheLuceneSearchHighlightHighlighter *) nil_chk(highlighter_)) getBestFragmentWithOrgApacheLuceneAnalysisAnalyzer:analyzer_ withNSString:fieldName withNSString:text];
    if (highlighted == nil) {
      return nil;
    }
    highlighted = [((JavaUtilRegexMatcher *) nil_chk([((JavaUtilRegexPattern *) nil_chk(OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern)) matcherWithJavaLangCharSequence:highlighted])) replaceAllWithNSString:@""];
    highlighted = [((JavaUtilRegexMatcher *) nil_chk([((JavaUtilRegexPattern *) nil_chk(OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern)) matcherWithJavaLangCharSequence:highlighted])) replaceAllWithNSString:@" "];
    if ([((NSString *) nil_chk(highlighted)) java_isEmpty]) {
      highlighted = nil;
    }
    return highlighted;
  }
  @catch (OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException *e) {
    return nil;
  }
  @catch (JavaIoIOException *e) {
    return nil;
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "I", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x0, 5, 6, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x0, 7, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initPackagePrivateWithOrgApacheLuceneSearchQuery:withOrgApacheLuceneAnalysisAnalyzer:);
  methods[1].selector = @selector(getFragmentLength);
  methods[2].selector = @selector(setFragmentLengthWithInt:);
  methods[3].selector = @selector(setLineFeedHTMLEscapeWithBoolean:);
  methods[4].selector = @selector(highlightOrOriginalWithNSString:withNSString:);
  methods[5].selector = @selector(highlightWithNSString:withNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "cleanUpPattern", "LJavaUtilRegexPattern;", .constantValue.asLong = 0, 0x18, -1, 8, -1, -1 },
    { "replaceLFPattern", "LJavaUtilRegexPattern;", .constantValue.asLong = 0, 0x18, -1, 9, -1, -1 },
    { "DEFAULT_FRAGMENT_LENGTH", "I", .constantValue.asInt = OrgLukhnosLucenestudyHighlightingHelper_DEFAULT_FRAGMENT_LENGTH, 0x19, -1, -1, -1, -1 },
    { "encoder_", "LOrgLukhnosLucenestudyMinimalHTMLEncoder;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "scorer_", "LOrgApacheLuceneSearchHighlightQueryScorer;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "highlighter_", "LOrgApacheLuceneSearchHighlightHighlighter;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "analyzer_", "LOrgApacheLuceneAnalysisAnalyzer;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "fragmentLength_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneSearchQuery;LOrgApacheLuceneAnalysisAnalyzer;", "setFragmentLength", "I", "setLineFeedHTMLEscape", "Z", "highlightOrOriginal", "LNSString;LNSString;", "highlight", &OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern, &OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudyHighlightingHelper = { "HighlightingHelper", "org.lukhnos.lucenestudy", ptrTable, methods, fields, 7, 0x0, 6, 8, -1, -1, -1, -1, -1 };
  return &_OrgLukhnosLucenestudyHighlightingHelper;
}

+ (void)initialize {
  if (self == [OrgLukhnosLucenestudyHighlightingHelper class]) {
    OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern = JavaUtilRegexPattern_compileWithNSString_(@"^[\\s\\p{Punct}&&[^<]]+");
    OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern = JavaUtilRegexPattern_compileWithNSString_(@"\\s*\\n+\\s*");
    J2OBJC_SET_INITIALIZED(OrgLukhnosLucenestudyHighlightingHelper)
  }
}

@end

void OrgLukhnosLucenestudyHighlightingHelper_initPackagePrivateWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgLukhnosLucenestudyHighlightingHelper *self, OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer) {
  NSObject_init(self);
  self->analyzer_ = analyzer;
  id<OrgApacheLuceneSearchHighlightFormatter> formatter = new_OrgApacheLuceneSearchHighlightSimpleHTMLFormatter_init();
  self->encoder_ = new_OrgLukhnosLucenestudyMinimalHTMLEncoder_init();
  self->scorer_ = new_OrgApacheLuceneSearchHighlightQueryScorer_initWithOrgApacheLuceneSearchQuery_(query);
  self->highlighter_ = new_OrgApacheLuceneSearchHighlightHighlighter_initWithOrgApacheLuceneSearchHighlightFormatter_withOrgApacheLuceneSearchHighlightEncoder_withOrgApacheLuceneSearchHighlightScorer_(formatter, self->encoder_, self->scorer_);
  self->fragmentLength_ = OrgLukhnosLucenestudyHighlightingHelper_DEFAULT_FRAGMENT_LENGTH;
  id<OrgApacheLuceneSearchHighlightFragmenter> fragmenter = new_OrgApacheLuceneSearchHighlightSimpleSpanFragmenter_initWithOrgApacheLuceneSearchHighlightQueryScorer_withInt_(self->scorer_, self->fragmentLength_);
  [self->highlighter_ setTextFragmenterWithOrgApacheLuceneSearchHighlightFragmenter:fragmenter];
}

OrgLukhnosLucenestudyHighlightingHelper *new_OrgLukhnosLucenestudyHighlightingHelper_initPackagePrivateWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer) {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudyHighlightingHelper, initPackagePrivateWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_, query, analyzer)
}

OrgLukhnosLucenestudyHighlightingHelper *create_OrgLukhnosLucenestudyHighlightingHelper_initPackagePrivateWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer) {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudyHighlightingHelper, initPackagePrivateWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_, query, analyzer)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudyHighlightingHelper)
