//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/HighlightingHelper.java
//

#ifndef _OrgLukhnosLucenestudyHighlightingHelper_H_
#define _OrgLukhnosLucenestudyHighlightingHelper_H_

#include "J2ObjC_header.h"

@class JavaUtilRegexPattern;
@class OrgApacheLuceneAnalysisAnalyzer;
@class OrgApacheLuceneSearchHighlightHighlighter;
@class OrgApacheLuceneSearchHighlightQueryScorer;
@class OrgApacheLuceneSearchQuery;

#define OrgLukhnosLucenestudyHighlightingHelper_DEFAULT_FRAGMENT_LENGTH 120

@interface OrgLukhnosLucenestudyHighlightingHelper : NSObject {
 @public
  OrgApacheLuceneSearchHighlightQueryScorer *scorer_;
  OrgApacheLuceneSearchHighlightHighlighter *highlighter_;
  OrgApacheLuceneAnalysisAnalyzer *analyzer_;
  jint fragmentLength_;
}

#pragma mark Package-Private

- (instancetype)initWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
               withOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer;

- (jint)getFragmentLength;

- (NSString *)highlightWithNSString:(NSString *)fieldName
                       withNSString:(NSString *)text;

- (NSString *)highlightOrOriginalWithNSString:(NSString *)fieldName
                                 withNSString:(NSString *)text;

- (void)setFragmentLengthWithInt:(jint)length;

@end

J2OBJC_STATIC_INIT(OrgLukhnosLucenestudyHighlightingHelper)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyHighlightingHelper, scorer_, OrgApacheLuceneSearchHighlightQueryScorer *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyHighlightingHelper, highlighter_, OrgApacheLuceneSearchHighlightHighlighter *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyHighlightingHelper, analyzer_, OrgApacheLuceneAnalysisAnalyzer *)

FOUNDATION_EXPORT JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyHighlightingHelper, cleanUpPattern_, JavaUtilRegexPattern *)

FOUNDATION_EXPORT JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyHighlightingHelper, replaceLFPattern_, JavaUtilRegexPattern *)

J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyHighlightingHelper, DEFAULT_FRAGMENT_LENGTH, jint)

FOUNDATION_EXPORT void OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgLukhnosLucenestudyHighlightingHelper *self, OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer);

FOUNDATION_EXPORT OrgLukhnosLucenestudyHighlightingHelper *new_OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyHighlightingHelper)

#endif // _OrgLukhnosLucenestudyHighlightingHelper_H_
