//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/HighlightingHelper.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/io/IOException.h"
#include "java/lang/AssertionError.h"
#include "java/lang/Exception.h"
#include "java/util/regex/Matcher.h"
#include "java/util/regex/Pattern.h"
#include "org/apache/lucene/analysis/Analyzer.h"
#include "org/apache/lucene/search/Query.h"
#include "org/apache/lucene/search/highlight/Encoder.h"
#include "org/apache/lucene/search/highlight/Formatter.h"
#include "org/apache/lucene/search/highlight/Fragmenter.h"
#include "org/apache/lucene/search/highlight/Highlighter.h"
#include "org/apache/lucene/search/highlight/InvalidTokenOffsetsException.h"
#include "org/apache/lucene/search/highlight/QueryScorer.h"
#include "org/apache/lucene/search/highlight/SimpleHTMLFormatter.h"
#include "org/apache/lucene/search/highlight/SimpleSpanFragmenter.h"
#include "org/lukhnos/lucenestudy/HighlightingHelper.h"
#include "org/lukhnos/lucenestudy/MinimalHTMLEncoder.h"

J2OBJC_INITIALIZED_DEFN(OrgLukhnosLucenestudyHighlightingHelper)

JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern;
JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern;

@implementation OrgLukhnosLucenestudyHighlightingHelper

- (instancetype)initWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
               withOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer {
  OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(self, query, analyzer);
  return self;
}

- (jint)getFragmentLength {
  return fragmentLength_;
}

- (void)setFragmentLengthWithInt:(jint)length {
  if (length < 1) {
    @throw new_JavaLangAssertionError_initWithId_(@"length must be at least 1");
  }
  if (fragmentLength_ != length) {
    id<OrgApacheLuceneSearchHighlightFragmenter> fragmenter = new_OrgApacheLuceneSearchHighlightSimpleSpanFragmenter_initWithOrgApacheLuceneSearchHighlightQueryScorer_withInt_(scorer_, length);
    [((OrgApacheLuceneSearchHighlightHighlighter *) nil_chk(highlighter_)) setTextFragmenterWithOrgApacheLuceneSearchHighlightFragmenter:fragmenter];
    fragmentLength_ = length;
  }
}

- (NSString *)highlightOrOriginalWithNSString:(NSString *)fieldName
                                 withNSString:(NSString *)text {
  if (text == nil) {
    return nil;
  }
  NSString *highlighted = [self highlightWithNSString:fieldName withNSString:text];
  if (highlighted != nil) {
    return highlighted;
  }
  jint cpCount = [text codePointCount:0 endIndex:((jint) [text length])];
  if (cpCount < fragmentLength_) {
    return text;
  }
  jint index = [text offsetByCodePoints:0 codePointOffset:fragmentLength_ - 1];
  return JreStrcat("$C", [text substring:0 endIndex:index], 0x2026);
}

- (NSString *)highlightWithNSString:(NSString *)fieldName
                       withNSString:(NSString *)text {
  if (text == nil) {
    return nil;
  }
  @try {
    NSString *highlighted = [((OrgApacheLuceneSearchHighlightHighlighter *) nil_chk(highlighter_)) getBestFragmentWithOrgApacheLuceneAnalysisAnalyzer:analyzer_ withNSString:fieldName withNSString:text];
    if (highlighted == nil) {
      return nil;
    }
    highlighted = [((JavaUtilRegexMatcher *) nil_chk([((JavaUtilRegexPattern *) nil_chk(OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern)) matcherWithJavaLangCharSequence:highlighted])) replaceAllWithNSString:@""];
    highlighted = [((JavaUtilRegexMatcher *) nil_chk([((JavaUtilRegexPattern *) nil_chk(OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern)) matcherWithJavaLangCharSequence:highlighted])) replaceAllWithNSString:@" "];
    if ([((NSString *) nil_chk(highlighted)) isEmpty]) {
      highlighted = nil;
    }
    return highlighted;
  }
  @catch (OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException *e) {
    return nil;
  }
  @catch (JavaIoIOException *e) {
    return nil;
  }
  @catch (JavaLangException *e) {
    return nil;
  }
}

+ (void)initialize {
  if (self == [OrgLukhnosLucenestudyHighlightingHelper class]) {
    OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern = JavaUtilRegexPattern_compileWithNSString_(@"^[\\s\\p{Punct}&&[^<]]+");
    OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern = JavaUtilRegexPattern_compileWithNSString_(@"\\n");
    J2OBJC_SET_INITIALIZED(OrgLukhnosLucenestudyHighlightingHelper)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgApacheLuceneSearchQuery:withOrgApacheLuceneAnalysisAnalyzer:", "HighlightingHelper", NULL, 0x0, NULL, NULL },
    { "getFragmentLength", NULL, "I", 0x0, NULL, NULL },
    { "setFragmentLengthWithInt:", "setFragmentLength", "V", 0x0, NULL, NULL },
    { "highlightOrOriginalWithNSString:withNSString:", "highlightOrOriginal", "Ljava.lang.String;", 0x0, NULL, NULL },
    { "highlightWithNSString:withNSString:", "highlight", "Ljava.lang.String;", 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "cleanUpPattern", "cleanUpPattern", 0x18, "Ljava.util.regex.Pattern;", &OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern, NULL, .constantValue.asLong = 0 },
    { "replaceLFPattern", "replaceLFPattern", 0x18, "Ljava.util.regex.Pattern;", &OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern, NULL, .constantValue.asLong = 0 },
    { "DEFAULT_FRAGMENT_LENGTH", "DEFAULT_FRAGMENT_LENGTH", 0x19, "I", NULL, NULL, .constantValue.asInt = OrgLukhnosLucenestudyHighlightingHelper_DEFAULT_FRAGMENT_LENGTH },
    { "scorer_", NULL, 0x10, "Lorg.apache.lucene.search.highlight.QueryScorer;", NULL, NULL, .constantValue.asLong = 0 },
    { "highlighter_", NULL, 0x10, "Lorg.apache.lucene.search.highlight.Highlighter;", NULL, NULL, .constantValue.asLong = 0 },
    { "analyzer_", NULL, 0x10, "Lorg.apache.lucene.analysis.Analyzer;", NULL, NULL, .constantValue.asLong = 0 },
    { "fragmentLength_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudyHighlightingHelper = { 2, "HighlightingHelper", "org.lukhnos.lucenestudy", NULL, 0x0, 5, methods, 7, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgLukhnosLucenestudyHighlightingHelper;
}

@end

void OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgLukhnosLucenestudyHighlightingHelper *self, OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer) {
  NSObject_init(self);
  self->analyzer_ = analyzer;
  id<OrgApacheLuceneSearchHighlightFormatter> formatter = new_OrgApacheLuceneSearchHighlightSimpleHTMLFormatter_init();
  id<OrgApacheLuceneSearchHighlightEncoder> encoder = new_OrgLukhnosLucenestudyMinimalHTMLEncoder_init();
  self->scorer_ = new_OrgApacheLuceneSearchHighlightQueryScorer_initWithOrgApacheLuceneSearchQuery_(query);
  self->highlighter_ = new_OrgApacheLuceneSearchHighlightHighlighter_initWithOrgApacheLuceneSearchHighlightFormatter_withOrgApacheLuceneSearchHighlightEncoder_withOrgApacheLuceneSearchHighlightScorer_(formatter, encoder, self->scorer_);
  self->fragmentLength_ = OrgLukhnosLucenestudyHighlightingHelper_DEFAULT_FRAGMENT_LENGTH;
  id<OrgApacheLuceneSearchHighlightFragmenter> fragmenter = new_OrgApacheLuceneSearchHighlightSimpleSpanFragmenter_initWithOrgApacheLuceneSearchHighlightQueryScorer_withInt_(self->scorer_, self->fragmentLength_);
  [self->highlighter_ setTextFragmenterWithOrgApacheLuceneSearchHighlightFragmenter:fragmenter];
}

OrgLukhnosLucenestudyHighlightingHelper *new_OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer) {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudyHighlightingHelper, initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_, query, analyzer)
}

OrgLukhnosLucenestudyHighlightingHelper *create_OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer) {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudyHighlightingHelper, initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_, query, analyzer)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudyHighlightingHelper)
