//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/HighlightingHelper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgLukhnosLucenestudyHighlightingHelper")
#ifdef RESTRICT_OrgLukhnosLucenestudyHighlightingHelper
#define INCLUDE_ALL_OrgLukhnosLucenestudyHighlightingHelper 0
#else
#define INCLUDE_ALL_OrgLukhnosLucenestudyHighlightingHelper 1
#endif
#undef RESTRICT_OrgLukhnosLucenestudyHighlightingHelper

#if !defined (OrgLukhnosLucenestudyHighlightingHelper_) && (INCLUDE_ALL_OrgLukhnosLucenestudyHighlightingHelper || defined(INCLUDE_OrgLukhnosLucenestudyHighlightingHelper))
#define OrgLukhnosLucenestudyHighlightingHelper_

@class JavaUtilRegexPattern;
@class OrgApacheLuceneAnalysisAnalyzer;
@class OrgApacheLuceneSearchHighlightHighlighter;
@class OrgApacheLuceneSearchHighlightQueryScorer;
@class OrgApacheLuceneSearchQuery;

@interface OrgLukhnosLucenestudyHighlightingHelper : NSObject {
 @public
  OrgApacheLuceneSearchHighlightQueryScorer *scorer_;
  OrgApacheLuceneSearchHighlightHighlighter *highlighter_;
  OrgApacheLuceneAnalysisAnalyzer *analyzer_;
  jint fragmentLength_;
}

#pragma mark Package-Private

- (instancetype)initWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
               withOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer;

- (jint)getFragmentLength;

- (NSString *)highlightWithNSString:(NSString *)fieldName
                       withNSString:(NSString *)text;

- (NSString *)highlightOrOriginalWithNSString:(NSString *)fieldName
                                 withNSString:(NSString *)text;

- (void)setFragmentLengthWithInt:(jint)length;

@end

J2OBJC_STATIC_INIT(OrgLukhnosLucenestudyHighlightingHelper)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyHighlightingHelper, scorer_, OrgApacheLuceneSearchHighlightQueryScorer *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyHighlightingHelper, highlighter_, OrgApacheLuceneSearchHighlightHighlighter *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyHighlightingHelper, analyzer_, OrgApacheLuceneAnalysisAnalyzer *)

inline JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_get_cleanUpPattern();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_cleanUpPattern;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgLukhnosLucenestudyHighlightingHelper, cleanUpPattern, JavaUtilRegexPattern *)

inline JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_get_replaceLFPattern();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT JavaUtilRegexPattern *OrgLukhnosLucenestudyHighlightingHelper_replaceLFPattern;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgLukhnosLucenestudyHighlightingHelper, replaceLFPattern, JavaUtilRegexPattern *)

inline jint OrgLukhnosLucenestudyHighlightingHelper_get_DEFAULT_FRAGMENT_LENGTH();
#define OrgLukhnosLucenestudyHighlightingHelper_DEFAULT_FRAGMENT_LENGTH 120
J2OBJC_STATIC_FIELD_CONSTANT(OrgLukhnosLucenestudyHighlightingHelper, DEFAULT_FRAGMENT_LENGTH, jint)

FOUNDATION_EXPORT void OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgLukhnosLucenestudyHighlightingHelper *self, OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer);

FOUNDATION_EXPORT OrgLukhnosLucenestudyHighlightingHelper *new_OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgLukhnosLucenestudyHighlightingHelper *create_OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(OrgApacheLuceneSearchQuery *query, OrgApacheLuceneAnalysisAnalyzer *analyzer);

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyHighlightingHelper)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgLukhnosLucenestudyHighlightingHelper")
