//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Indexer.java
//

#ifndef _OrgLukhnosLucenestudyIndexer_H_
#define _OrgLukhnosLucenestudyIndexer_H_

#include "J2ObjC_header.h"
#include "java/lang/AutoCloseable.h"

@class JavaLangInteger;
@class OrgApacheLuceneAnalysisAnalyzer;
@class OrgApacheLuceneDocumentDocument;
@class OrgApacheLuceneIndexIndexWriter;
@class OrgLukhnosLucenestudyDocument;
@class OrgLukhnosPortmobileFilePath;
@protocol JavaUtilList;

@interface OrgLukhnosLucenestudyIndexer : NSObject < JavaLangAutoCloseable > {
 @public
  OrgApacheLuceneIndexIndexWriter *indexWriter_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)indexRoot;

- (instancetype)initWithNSString:(NSString *)indexRoot
                     withBoolean:(jboolean)appendIfExists;

- (void)addDocumentsWithJavaUtilList:(id<JavaUtilList>)docs;

- (void)close;

+ (OrgApacheLuceneAnalysisAnalyzer *)getAnalyzer;

#pragma mark Package-Private

+ (OrgLukhnosLucenestudyDocument *)fromLuceneDocumentWithOrgApacheLuceneDocumentDocument:(OrgApacheLuceneDocumentDocument *)luceneDoc;

+ (JavaLangInteger *)getIntegerWithOrgApacheLuceneDocumentDocument:(OrgApacheLuceneDocumentDocument *)luceneDoc
                                                      withNSString:(NSString *)fieldName;

+ (OrgLukhnosPortmobileFilePath *)getMainIndexPathWithOrgLukhnosPortmobileFilePath:(OrgLukhnosPortmobileFilePath *)indexRoot;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudyIndexer)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyIndexer, indexWriter_, OrgApacheLuceneIndexIndexWriter *)

FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyIndexer, TITLE_FIELD_NAME_, NSString *)

FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudyIndexer_YEAR_FIELD_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyIndexer, YEAR_FIELD_NAME_, NSString *)

FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudyIndexer_RATING_FIELD_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyIndexer, RATING_FIELD_NAME_, NSString *)

FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudyIndexer_POSITIVE_FIELD_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyIndexer, POSITIVE_FIELD_NAME_, NSString *)

FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudyIndexer_REVIEW_FIELD_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyIndexer, REVIEW_FIELD_NAME_, NSString *)

FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudyIndexer_SOURCE_FIELD_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyIndexer, SOURCE_FIELD_NAME_, NSString *)

FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudyIndexer_INDEX_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudyIndexer, INDEX_NAME_, NSString *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudyIndexer_initWithNSString_(OrgLukhnosLucenestudyIndexer *self, NSString *indexRoot);

FOUNDATION_EXPORT OrgLukhnosLucenestudyIndexer *new_OrgLukhnosLucenestudyIndexer_initWithNSString_(NSString *indexRoot) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_(OrgLukhnosLucenestudyIndexer *self, NSString *indexRoot, jboolean appendIfExists);

FOUNDATION_EXPORT OrgLukhnosLucenestudyIndexer *new_OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_(NSString *indexRoot, jboolean appendIfExists) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneAnalysisAnalyzer *OrgLukhnosLucenestudyIndexer_getAnalyzer();

FOUNDATION_EXPORT JavaLangInteger *OrgLukhnosLucenestudyIndexer_getIntegerWithOrgApacheLuceneDocumentDocument_withNSString_(OrgApacheLuceneDocumentDocument *luceneDoc, NSString *fieldName);

FOUNDATION_EXPORT OrgLukhnosLucenestudyDocument *OrgLukhnosLucenestudyIndexer_fromLuceneDocumentWithOrgApacheLuceneDocumentDocument_(OrgApacheLuceneDocumentDocument *luceneDoc);

FOUNDATION_EXPORT OrgLukhnosPortmobileFilePath *OrgLukhnosLucenestudyIndexer_getMainIndexPathWithOrgLukhnosPortmobileFilePath_(OrgLukhnosPortmobileFilePath *indexRoot);

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyIndexer)

#endif // _OrgLukhnosLucenestudyIndexer_H_
