//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Indexer.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Integer.h"
#include "java/util/List.h"
#include "org/apache/lucene/analysis/Analyzer.h"
#include "org/apache/lucene/analysis/en/EnglishAnalyzer.h"
#include "org/apache/lucene/document/Document.h"
#include "org/apache/lucene/document/Field.h"
#include "org/apache/lucene/document/IntField.h"
#include "org/apache/lucene/document/NumericDocValuesField.h"
#include "org/apache/lucene/document/SortedDocValuesField.h"
#include "org/apache/lucene/document/StringField.h"
#include "org/apache/lucene/document/TextField.h"
#include "org/apache/lucene/index/IndexWriter.h"
#include "org/apache/lucene/index/IndexWriterConfig.h"
#include "org/apache/lucene/index/IndexableField.h"
#include "org/apache/lucene/queryparser/classic/MultiFieldQueryParser.h"
#include "org/apache/lucene/queryparser/classic/QueryParser.h"
#include "org/apache/lucene/search/Query.h"
#include "org/apache/lucene/store/Directory.h"
#include "org/apache/lucene/store/FSDirectory.h"
#include "org/apache/lucene/util/BytesRef.h"
#include "org/lukhnos/lucenestudy/Document.h"
#include "org/lukhnos/lucenestudy/Indexer.h"
#include "org/lukhnos/portmobile/file/Path.h"
#include "org/lukhnos/portmobile/file/Paths.h"

#if !__has_feature(objc_arc)
#error "org/lukhnos/lucenestudy/Indexer must be compiled with ARC (-fobjc-arc)"
#endif

NSString *OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME = @"title";
NSString *OrgLukhnosLucenestudyIndexer_YEAR_FIELD_NAME = @"year";
NSString *OrgLukhnosLucenestudyIndexer_RATING_FIELD_NAME = @"rating";
NSString *OrgLukhnosLucenestudyIndexer_POSITIVE_FIELD_NAME = @"positive";
NSString *OrgLukhnosLucenestudyIndexer_REVIEW_FIELD_NAME = @"review";
NSString *OrgLukhnosLucenestudyIndexer_SOURCE_FIELD_NAME = @"source";
NSString *OrgLukhnosLucenestudyIndexer_INDEX_NAME = @"main";

@implementation OrgLukhnosLucenestudyIndexer

- (instancetype)initWithNSString:(NSString *)indexRoot {
  OrgLukhnosLucenestudyIndexer_initWithNSString_(self, indexRoot);
  return self;
}

- (instancetype)initWithNSString:(NSString *)indexRoot
                     withBoolean:(jboolean)appendIfExists {
  OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_(self, indexRoot, appendIfExists);
  return self;
}

+ (OrgApacheLuceneAnalysisAnalyzer *)getAnalyzer {
  return OrgLukhnosLucenestudyIndexer_getAnalyzer();
}

+ (OrgApacheLuceneSearchQuery *)parseQueryWithOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer
                                                                 withNSString:(NSString *)queryStr {
  return OrgLukhnosLucenestudyIndexer_parseQueryWithOrgApacheLuceneAnalysisAnalyzer_withNSString_(analyzer, queryStr);
}

+ (JavaLangInteger *)getIntegerWithOrgApacheLuceneDocumentDocument:(OrgApacheLuceneDocumentDocument *)luceneDoc
                                                      withNSString:(NSString *)fieldName {
  return OrgLukhnosLucenestudyIndexer_getIntegerWithOrgApacheLuceneDocumentDocument_withNSString_(luceneDoc, fieldName);
}

+ (OrgLukhnosLucenestudyDocument *)fromLuceneDocumentWithOrgApacheLuceneDocumentDocument:(OrgApacheLuceneDocumentDocument *)luceneDoc {
  return OrgLukhnosLucenestudyIndexer_fromLuceneDocumentWithOrgApacheLuceneDocumentDocument_(luceneDoc);
}

+ (OrgLukhnosPortmobileFilePath *)getMainIndexPathWithOrgLukhnosPortmobileFilePath:(OrgLukhnosPortmobileFilePath *)indexRoot {
  return OrgLukhnosLucenestudyIndexer_getMainIndexPathWithOrgLukhnosPortmobileFilePath_(indexRoot);
}

- (void)close {
  [((OrgApacheLuceneIndexIndexWriter *) nil_chk(indexWriter_)) close];
}

- (void)addDocumentsWithJavaUtilList:(id<JavaUtilList>)docs {
  OrgApacheLuceneDocumentField *titleField = new_OrgApacheLuceneDocumentTextField_initWithNSString_withNSString_withOrgApacheLuceneDocumentField_Store_(OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME, @"", JreLoadEnum(OrgApacheLuceneDocumentField_Store, YES));
  OrgApacheLuceneDocumentField *titleDocsValueField = new_OrgApacheLuceneDocumentSortedDocValuesField_initWithNSString_withOrgApacheLuceneUtilBytesRef_(OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME, new_OrgApacheLuceneUtilBytesRef_initWithInt_(0));
  OrgApacheLuceneDocumentField *yearField = new_OrgApacheLuceneDocumentIntField_initWithNSString_withInt_withOrgApacheLuceneDocumentField_Store_(OrgLukhnosLucenestudyIndexer_YEAR_FIELD_NAME, 0, JreLoadEnum(OrgApacheLuceneDocumentField_Store, YES));
  OrgApacheLuceneDocumentField *yearDocsValueField = new_OrgApacheLuceneDocumentNumericDocValuesField_initWithNSString_withLong_(OrgLukhnosLucenestudyIndexer_YEAR_FIELD_NAME, 0LL);
  OrgApacheLuceneDocumentField *ratingField = new_OrgApacheLuceneDocumentIntField_initWithNSString_withInt_withOrgApacheLuceneDocumentField_Store_(OrgLukhnosLucenestudyIndexer_RATING_FIELD_NAME, 0, JreLoadEnum(OrgApacheLuceneDocumentField_Store, YES));
  OrgApacheLuceneDocumentField *ratingDocsValueField = new_OrgApacheLuceneDocumentNumericDocValuesField_initWithNSString_withLong_(OrgLukhnosLucenestudyIndexer_RATING_FIELD_NAME, 0LL);
  OrgApacheLuceneDocumentField *positiveField = new_OrgApacheLuceneDocumentIntField_initWithNSString_withInt_withOrgApacheLuceneDocumentField_Store_(OrgLukhnosLucenestudyIndexer_POSITIVE_FIELD_NAME, 0, JreLoadEnum(OrgApacheLuceneDocumentField_Store, YES));
  OrgApacheLuceneDocumentField *reviewField = new_OrgApacheLuceneDocumentTextField_initWithNSString_withNSString_withOrgApacheLuceneDocumentField_Store_(OrgLukhnosLucenestudyIndexer_REVIEW_FIELD_NAME, @"", JreLoadEnum(OrgApacheLuceneDocumentField_Store, YES));
  OrgApacheLuceneDocumentField *sourceField = new_OrgApacheLuceneDocumentStringField_initWithNSString_withNSString_withOrgApacheLuceneDocumentField_Store_(OrgLukhnosLucenestudyIndexer_SOURCE_FIELD_NAME, @"", JreLoadEnum(OrgApacheLuceneDocumentField_Store, YES));
  for (OrgLukhnosLucenestudyDocument * __strong doc in nil_chk(docs)) {
    OrgApacheLuceneDocumentDocument *luceneDoc = new_OrgApacheLuceneDocumentDocument_init();
    if (((OrgLukhnosLucenestudyDocument *) nil_chk(doc))->title_ != nil && ![doc->title_ java_isEmpty]) {
      [titleField setStringValueWithNSString:doc->title_];
      [luceneDoc addWithOrgApacheLuceneIndexIndexableField:titleField];
      [titleDocsValueField setBytesValueWithOrgApacheLuceneUtilBytesRef:new_OrgApacheLuceneUtilBytesRef_initWithJavaLangCharSequence_(doc->title_)];
      [luceneDoc addWithOrgApacheLuceneIndexIndexableField:titleDocsValueField];
    }
    [yearField setIntValueWithInt:doc->year_];
    [luceneDoc addWithOrgApacheLuceneIndexIndexableField:yearField];
    [yearDocsValueField setLongValueWithLong:(jlong) doc->year_];
    [luceneDoc addWithOrgApacheLuceneIndexIndexableField:yearDocsValueField];
    [ratingField setIntValueWithInt:doc->rating_];
    [luceneDoc addWithOrgApacheLuceneIndexIndexableField:ratingField];
    [ratingDocsValueField setLongValueWithLong:(jlong) doc->rating_];
    [luceneDoc addWithOrgApacheLuceneIndexIndexableField:ratingDocsValueField];
    [positiveField setIntValueWithInt:doc->positive_ ? 1 : 0];
    [luceneDoc addWithOrgApacheLuceneIndexIndexableField:positiveField];
    if (doc->review_ != nil && ![doc->review_ java_isEmpty]) {
      [reviewField setStringValueWithNSString:doc->review_];
      [luceneDoc addWithOrgApacheLuceneIndexIndexableField:reviewField];
    }
    if (doc->source_ != nil && ![doc->source_ java_isEmpty]) {
      [sourceField setStringValueWithNSString:doc->source_];
      [luceneDoc addWithOrgApacheLuceneIndexIndexableField:sourceField];
    }
    [((OrgApacheLuceneIndexIndexWriter *) nil_chk(indexWriter_)) addDocumentWithJavaLangIterable:luceneDoc];
  }
  [((OrgApacheLuceneIndexIndexWriter *) nil_chk(indexWriter_)) commit];
}

- (void)deleteDocumentsByQueryWithNSString:(NSString *)queryStr {
  OrgApacheLuceneSearchQuery *query = OrgLukhnosLucenestudyIndexer_parseQueryWithOrgApacheLuceneAnalysisAnalyzer_withNSString_([((OrgApacheLuceneIndexIndexWriter *) nil_chk(indexWriter_)) getAnalyzer], queryStr);
  [indexWriter_ deleteDocumentsWithOrgApacheLuceneSearchQueryArray:[IOSObjectArray newArrayWithObjects:(id[]){ query } count:1 type:OrgApacheLuceneSearchQuery_class_()]];
  [indexWriter_ commit];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, 1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, 1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneAnalysisAnalyzer;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchQuery;", 0x9, 3, 4, 5, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x8, 6, 7, -1, -1, -1, -1 },
    { NULL, "LOrgLukhnosLucenestudyDocument;", 0x8, 8, 9, -1, -1, -1, -1 },
    { NULL, "LOrgLukhnosPortmobileFilePath;", 0x8, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 12, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, 1, 15, -1, -1 },
    { NULL, "V", 0x1, 16, 0, 17, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(initWithNSString:withBoolean:);
  methods[2].selector = @selector(getAnalyzer);
  methods[3].selector = @selector(parseQueryWithOrgApacheLuceneAnalysisAnalyzer:withNSString:);
  methods[4].selector = @selector(getIntegerWithOrgApacheLuceneDocumentDocument:withNSString:);
  methods[5].selector = @selector(fromLuceneDocumentWithOrgApacheLuceneDocumentDocument:);
  methods[6].selector = @selector(getMainIndexPathWithOrgLukhnosPortmobileFilePath:);
  methods[7].selector = @selector(close);
  methods[8].selector = @selector(addDocumentsWithJavaUtilList:);
  methods[9].selector = @selector(deleteDocumentsByQueryWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "TITLE_FIELD_NAME", "LNSString;", .constantValue.asLong = 0, 0x18, -1, 18, -1, -1 },
    { "YEAR_FIELD_NAME", "LNSString;", .constantValue.asLong = 0, 0x18, -1, 19, -1, -1 },
    { "RATING_FIELD_NAME", "LNSString;", .constantValue.asLong = 0, 0x18, -1, 20, -1, -1 },
    { "POSITIVE_FIELD_NAME", "LNSString;", .constantValue.asLong = 0, 0x18, -1, 21, -1, -1 },
    { "REVIEW_FIELD_NAME", "LNSString;", .constantValue.asLong = 0, 0x18, -1, 22, -1, -1 },
    { "SOURCE_FIELD_NAME", "LNSString;", .constantValue.asLong = 0, 0x18, -1, 23, -1, -1 },
    { "INDEX_NAME", "LNSString;", .constantValue.asLong = 0, 0x18, -1, 24, -1, -1 },
    { "indexWriter_", "LOrgApacheLuceneIndexIndexWriter;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "LJavaIoIOException;", "LNSString;Z", "parseQuery", "LOrgApacheLuceneAnalysisAnalyzer;LNSString;", "LOrgApacheLuceneQueryparserClassicParseException;", "getInteger", "LOrgApacheLuceneDocumentDocument;LNSString;", "fromLuceneDocument", "LOrgApacheLuceneDocumentDocument;", "getMainIndexPath", "LOrgLukhnosPortmobileFilePath;", "LJavaLangException;", "addDocuments", "LJavaUtilList;", "(Ljava/util/List<Lorg/lukhnos/lucenestudy/Document;>;)V", "deleteDocumentsByQuery", "LOrgApacheLuceneQueryparserClassicParseException;LJavaIoIOException;", &OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME, &OrgLukhnosLucenestudyIndexer_YEAR_FIELD_NAME, &OrgLukhnosLucenestudyIndexer_RATING_FIELD_NAME, &OrgLukhnosLucenestudyIndexer_POSITIVE_FIELD_NAME, &OrgLukhnosLucenestudyIndexer_REVIEW_FIELD_NAME, &OrgLukhnosLucenestudyIndexer_SOURCE_FIELD_NAME, &OrgLukhnosLucenestudyIndexer_INDEX_NAME };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudyIndexer = { "Indexer", "org.lukhnos.lucenestudy", ptrTable, methods, fields, 7, 0x1, 10, 8, -1, -1, -1, -1, -1 };
  return &_OrgLukhnosLucenestudyIndexer;
}

@end

void OrgLukhnosLucenestudyIndexer_initWithNSString_(OrgLukhnosLucenestudyIndexer *self, NSString *indexRoot) {
  OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_(self, indexRoot, false);
}

OrgLukhnosLucenestudyIndexer *new_OrgLukhnosLucenestudyIndexer_initWithNSString_(NSString *indexRoot) {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudyIndexer, initWithNSString_, indexRoot)
}

OrgLukhnosLucenestudyIndexer *create_OrgLukhnosLucenestudyIndexer_initWithNSString_(NSString *indexRoot) {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudyIndexer, initWithNSString_, indexRoot)
}

void OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_(OrgLukhnosLucenestudyIndexer *self, NSString *indexRoot, jboolean appendIfExists) {
  NSObject_init(self);
  OrgLukhnosPortmobileFilePath *indexRootPath = OrgLukhnosPortmobileFilePaths_getWithNSString_(indexRoot);
  OrgApacheLuceneAnalysisAnalyzer *analyzer = OrgLukhnosLucenestudyIndexer_getAnalyzer();
  OrgApacheLuceneStoreDirectory *mainIndexDir = OrgApacheLuceneStoreFSDirectory_openWithOrgLukhnosPortmobileFilePath_(OrgLukhnosLucenestudyIndexer_getMainIndexPathWithOrgLukhnosPortmobileFilePath_(indexRootPath));
  OrgApacheLuceneIndexIndexWriterConfig *mainIndexWriterConfig = new_OrgApacheLuceneIndexIndexWriterConfig_initWithOrgApacheLuceneAnalysisAnalyzer_(analyzer);
  if (appendIfExists) {
    (void) [mainIndexWriterConfig setOpenModeWithOrgApacheLuceneIndexIndexWriterConfig_OpenMode:JreLoadEnum(OrgApacheLuceneIndexIndexWriterConfig_OpenMode, CREATE_OR_APPEND)];
  }
  else {
    (void) [mainIndexWriterConfig setOpenModeWithOrgApacheLuceneIndexIndexWriterConfig_OpenMode:JreLoadEnum(OrgApacheLuceneIndexIndexWriterConfig_OpenMode, CREATE)];
  }
  self->indexWriter_ = new_OrgApacheLuceneIndexIndexWriter_initWithOrgApacheLuceneStoreDirectory_withOrgApacheLuceneIndexIndexWriterConfig_(mainIndexDir, mainIndexWriterConfig);
}

OrgLukhnosLucenestudyIndexer *new_OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_(NSString *indexRoot, jboolean appendIfExists) {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudyIndexer, initWithNSString_withBoolean_, indexRoot, appendIfExists)
}

OrgLukhnosLucenestudyIndexer *create_OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_(NSString *indexRoot, jboolean appendIfExists) {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudyIndexer, initWithNSString_withBoolean_, indexRoot, appendIfExists)
}

OrgApacheLuceneAnalysisAnalyzer *OrgLukhnosLucenestudyIndexer_getAnalyzer() {
  OrgLukhnosLucenestudyIndexer_initialize();
  return new_OrgApacheLuceneAnalysisEnEnglishAnalyzer_init();
}

OrgApacheLuceneSearchQuery *OrgLukhnosLucenestudyIndexer_parseQueryWithOrgApacheLuceneAnalysisAnalyzer_withNSString_(OrgApacheLuceneAnalysisAnalyzer *analyzer, NSString *queryStr) {
  OrgLukhnosLucenestudyIndexer_initialize();
  IOSObjectArray *fields = [IOSObjectArray newArrayWithObjects:(id[]){ OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME, OrgLukhnosLucenestudyIndexer_REVIEW_FIELD_NAME } count:2 type:NSString_class_()];
  OrgApacheLuceneQueryparserClassicQueryParser *parser = new_OrgApacheLuceneQueryparserClassicMultiFieldQueryParser_initWithNSStringArray_withOrgApacheLuceneAnalysisAnalyzer_(fields, analyzer);
  return [parser parseWithNSString:queryStr];
}

JavaLangInteger *OrgLukhnosLucenestudyIndexer_getIntegerWithOrgApacheLuceneDocumentDocument_withNSString_(OrgApacheLuceneDocumentDocument *luceneDoc, NSString *fieldName) {
  OrgLukhnosLucenestudyIndexer_initialize();
  id<OrgApacheLuceneIndexIndexableField> field = [((OrgApacheLuceneDocumentDocument *) nil_chk(luceneDoc)) getFieldWithNSString:fieldName];
  if (field != nil) {
    NSNumber *number = [field numericValue];
    if (number != nil) {
      return JavaLangInteger_valueOfWithInt_([number intValue]);
    }
  }
  return nil;
}

OrgLukhnosLucenestudyDocument *OrgLukhnosLucenestudyIndexer_fromLuceneDocumentWithOrgApacheLuceneDocumentDocument_(OrgApacheLuceneDocumentDocument *luceneDoc) {
  OrgLukhnosLucenestudyIndexer_initialize();
  NSString *title = [((OrgApacheLuceneDocumentDocument *) nil_chk(luceneDoc)) getWithNSString:OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME];
  JavaLangInteger *number;
  jint year;
  number = OrgLukhnosLucenestudyIndexer_getIntegerWithOrgApacheLuceneDocumentDocument_withNSString_(luceneDoc, OrgLukhnosLucenestudyIndexer_YEAR_FIELD_NAME);
  year = (number == nil) ? 0 : [((JavaLangInteger *) nil_chk(number)) intValue];
  jint rating;
  number = OrgLukhnosLucenestudyIndexer_getIntegerWithOrgApacheLuceneDocumentDocument_withNSString_(luceneDoc, OrgLukhnosLucenestudyIndexer_RATING_FIELD_NAME);
  rating = (number == nil) ? 0 : [((JavaLangInteger *) nil_chk(number)) intValue];
  jboolean positive;
  number = OrgLukhnosLucenestudyIndexer_getIntegerWithOrgApacheLuceneDocumentDocument_withNSString_(luceneDoc, OrgLukhnosLucenestudyIndexer_POSITIVE_FIELD_NAME);
  positive = (number == nil) ? false : ([((JavaLangInteger *) nil_chk(number)) intValue] != 0);
  NSString *review = [luceneDoc getWithNSString:OrgLukhnosLucenestudyIndexer_REVIEW_FIELD_NAME];
  NSString *source = [luceneDoc getWithNSString:OrgLukhnosLucenestudyIndexer_SOURCE_FIELD_NAME];
  return new_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(title, year, rating, positive, review, source);
}

OrgLukhnosPortmobileFilePath *OrgLukhnosLucenestudyIndexer_getMainIndexPathWithOrgLukhnosPortmobileFilePath_(OrgLukhnosPortmobileFilePath *indexRoot) {
  OrgLukhnosLucenestudyIndexer_initialize();
  return [((OrgLukhnosPortmobileFilePath *) nil_chk(indexRoot)) resolveWithNSString:OrgLukhnosLucenestudyIndexer_INDEX_NAME];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudyIndexer)
