//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/MinimalHTMLEncoder.java
//

#ifndef _OrgLukhnosLucenestudyMinimalHTMLEncoder_H_
#define _OrgLukhnosLucenestudyMinimalHTMLEncoder_H_

#include "J2ObjC_header.h"
#include "org/apache/lucene/search/highlight/Encoder.h"

@interface OrgLukhnosLucenestudyMinimalHTMLEncoder : NSObject < OrgApacheLuceneSearchHighlightEncoder >

#pragma mark Public

- (instancetype)init;

- (NSString *)encodeTextWithNSString:(NSString *)originalText;

+ (NSString *)htmlEncodeWithNSString:(NSString *)plainText;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudyMinimalHTMLEncoder)

FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudyMinimalHTMLEncoder_htmlEncodeWithNSString_(NSString *plainText);

FOUNDATION_EXPORT void OrgLukhnosLucenestudyMinimalHTMLEncoder_init(OrgLukhnosLucenestudyMinimalHTMLEncoder *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudyMinimalHTMLEncoder *new_OrgLukhnosLucenestudyMinimalHTMLEncoder_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyMinimalHTMLEncoder)

#endif // _OrgLukhnosLucenestudyMinimalHTMLEncoder_H_
