//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/SearchResult.java
//

#ifndef _OrgLukhnosLucenestudySearchResult_H_
#define _OrgLukhnosLucenestudySearchResult_H_

#include "J2ObjC_header.h"

@class OrgApacheLuceneSearchQuery;
@class OrgApacheLuceneSearchScoreDoc;
@class OrgApacheLuceneSearchSort;
@class OrgLukhnosLucenestudyDocument;
@class OrgLukhnosLucenestudyHighlightingHelper;
@protocol JavaUtilList;

@interface OrgLukhnosLucenestudySearchResult : NSObject {
 @public
  jint totalHits_;
  id<JavaUtilList> documents_;
  OrgApacheLuceneSearchScoreDoc *lastScoreDoc_;
  OrgApacheLuceneSearchQuery *query_;
  OrgApacheLuceneSearchSort *sort_;
  OrgLukhnosLucenestudyHighlightingHelper *highlightingHelper_;
}

#pragma mark Public

- (NSString *)getFullHighlightedReviewWithOrgLukhnosLucenestudyDocument:(OrgLukhnosLucenestudyDocument *)doc;

- (NSString *)getHighlightedReviewWithOrgLukhnosLucenestudyDocument:(OrgLukhnosLucenestudyDocument *)doc;

- (NSString *)getHighlightedTitleWithOrgLukhnosLucenestudyDocument:(OrgLukhnosLucenestudyDocument *)doc;

- (jboolean)hasMore;

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)totalHits
           withJavaUtilList:(id<JavaUtilList>)documents
withOrgApacheLuceneSearchScoreDoc:(OrgApacheLuceneSearchScoreDoc *)lastScoreDoc
withOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
withOrgApacheLuceneSearchSort:(OrgApacheLuceneSearchSort *)sort
withOrgLukhnosLucenestudyHighlightingHelper:(OrgLukhnosLucenestudyHighlightingHelper *)highlightingHelper;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudySearchResult)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearchResult, documents_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearchResult, lastScoreDoc_, OrgApacheLuceneSearchScoreDoc *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearchResult, query_, OrgApacheLuceneSearchQuery *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearchResult, sort_, OrgApacheLuceneSearchSort *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearchResult, highlightingHelper_, OrgLukhnosLucenestudyHighlightingHelper *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudySearchResult_initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_(OrgLukhnosLucenestudySearchResult *self, jint totalHits, id<JavaUtilList> documents, OrgApacheLuceneSearchScoreDoc *lastScoreDoc, OrgApacheLuceneSearchQuery *query, OrgApacheLuceneSearchSort *sort, OrgLukhnosLucenestudyHighlightingHelper *highlightingHelper);

FOUNDATION_EXPORT OrgLukhnosLucenestudySearchResult *new_OrgLukhnosLucenestudySearchResult_initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_(jint totalHits, id<JavaUtilList> documents, OrgApacheLuceneSearchScoreDoc *lastScoreDoc, OrgApacheLuceneSearchQuery *query, OrgApacheLuceneSearchSort *sort, OrgLukhnosLucenestudyHighlightingHelper *highlightingHelper) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudySearchResult)

#endif // _OrgLukhnosLucenestudySearchResult_H_
