//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Searcher.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgLukhnosLucenestudySearcher")
#ifdef RESTRICT_OrgLukhnosLucenestudySearcher
#define INCLUDE_ALL_OrgLukhnosLucenestudySearcher 0
#else
#define INCLUDE_ALL_OrgLukhnosLucenestudySearcher 1
#endif
#undef RESTRICT_OrgLukhnosLucenestudySearcher

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgLukhnosLucenestudySearcher_) && (INCLUDE_ALL_OrgLukhnosLucenestudySearcher || defined(INCLUDE_OrgLukhnosLucenestudySearcher))
#define OrgLukhnosLucenestudySearcher_

#define RESTRICT_JavaLangAutoCloseable 1
#define INCLUDE_JavaLangAutoCloseable 1
#include "java/lang/AutoCloseable.h"

@class OrgApacheLuceneAnalysisAnalyzer;
@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneSearchQuery;
@class OrgApacheLuceneSearchScoreDoc;
@class OrgApacheLuceneSearchSort;
@class OrgLukhnosLucenestudySearchResult;
@class OrgLukhnosLucenestudySearcher_SortBy;

@interface OrgLukhnosLucenestudySearcher : NSObject < JavaLangAutoCloseable > {
 @public
  OrgApacheLuceneAnalysisAnalyzer *analyzer_;
  OrgApacheLuceneIndexIndexReader *indexReader_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)indexRoot;

- (void)close;

- (OrgLukhnosLucenestudySearchResult *)searchWithNSString:(NSString *)queryStr
                                                  withInt:(jint)maxCount;

- (OrgLukhnosLucenestudySearchResult *)searchWithNSString:(NSString *)queryStr
                 withOrgLukhnosLucenestudySearcher_SortBy:(OrgLukhnosLucenestudySearcher_SortBy *)sortBy
                                                  withInt:(jint)maxCount;

- (OrgLukhnosLucenestudySearchResult *)searchAfterWithOrgLukhnosLucenestudySearchResult:(OrgLukhnosLucenestudySearchResult *)result
                                                                                withInt:(jint)maxCount;

#pragma mark Package-Private

- (OrgLukhnosLucenestudySearchResult *)searchAfterWithOrgApacheLuceneSearchScoreDoc:(OrgApacheLuceneSearchScoreDoc *)lastScoreDoc
                                                     withOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
                                                      withOrgApacheLuceneSearchSort:(OrgApacheLuceneSearchSort *)sort
                                                                            withInt:(jint)maxCount;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudySearcher)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearcher, analyzer_, OrgApacheLuceneAnalysisAnalyzer *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearcher, indexReader_, OrgApacheLuceneIndexIndexReader *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudySearcher_initWithNSString_(OrgLukhnosLucenestudySearcher *self, NSString *indexRoot);

FOUNDATION_EXPORT OrgLukhnosLucenestudySearcher *new_OrgLukhnosLucenestudySearcher_initWithNSString_(NSString *indexRoot) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgLukhnosLucenestudySearcher *create_OrgLukhnosLucenestudySearcher_initWithNSString_(NSString *indexRoot);

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudySearcher)

#endif

#if !defined (OrgLukhnosLucenestudySearcher_SortBy_) && (INCLUDE_ALL_OrgLukhnosLucenestudySearcher || defined(INCLUDE_OrgLukhnosLucenestudySearcher_SortBy))
#define OrgLukhnosLucenestudySearcher_SortBy_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class OrgApacheLuceneSearchSort;

typedef NS_ENUM(NSUInteger, OrgLukhnosLucenestudySearcher_SortBy_Enum) {
  OrgLukhnosLucenestudySearcher_SortBy_Enum_RELEVANCE = 0,
  OrgLukhnosLucenestudySearcher_SortBy_Enum_DOCUMENT_ORDER = 1,
  OrgLukhnosLucenestudySearcher_SortBy_Enum_TITLE = 2,
  OrgLukhnosLucenestudySearcher_SortBy_Enum_YEAR = 3,
  OrgLukhnosLucenestudySearcher_SortBy_Enum_RATING = 4,
};

@interface OrgLukhnosLucenestudySearcher_SortBy : JavaLangEnum {
 @public
  OrgApacheLuceneSearchSort *sort_;
}

#pragma mark Public

+ (OrgLukhnosLucenestudySearcher_SortBy *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgLukhnosLucenestudySearcher_SortBy_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(OrgLukhnosLucenestudySearcher_SortBy)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_values_[];

inline OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_get_RELEVANCE(void);
J2OBJC_ENUM_CONSTANT(OrgLukhnosLucenestudySearcher_SortBy, RELEVANCE)

inline OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_get_DOCUMENT_ORDER(void);
J2OBJC_ENUM_CONSTANT(OrgLukhnosLucenestudySearcher_SortBy, DOCUMENT_ORDER)

inline OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_get_TITLE(void);
J2OBJC_ENUM_CONSTANT(OrgLukhnosLucenestudySearcher_SortBy, TITLE)

inline OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_get_YEAR(void);
J2OBJC_ENUM_CONSTANT(OrgLukhnosLucenestudySearcher_SortBy, YEAR)

inline OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_get_RATING(void);
J2OBJC_ENUM_CONSTANT(OrgLukhnosLucenestudySearcher_SortBy, RATING)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearcher_SortBy, sort_, OrgApacheLuceneSearchSort *)

FOUNDATION_EXPORT IOSObjectArray *OrgLukhnosLucenestudySearcher_SortBy_values(void);

FOUNDATION_EXPORT OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudySearcher_SortBy)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgLukhnosLucenestudySearcher")
