//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Searcher.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/AssertionError.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"
#include "org/apache/lucene/analysis/Analyzer.h"
#include "org/apache/lucene/document/Document.h"
#include "org/apache/lucene/index/DirectoryReader.h"
#include "org/apache/lucene/index/IndexReader.h"
#include "org/apache/lucene/search/IndexSearcher.h"
#include "org/apache/lucene/search/Query.h"
#include "org/apache/lucene/search/ScoreDoc.h"
#include "org/apache/lucene/search/Sort.h"
#include "org/apache/lucene/search/SortField.h"
#include "org/apache/lucene/search/TopDocs.h"
#include "org/apache/lucene/search/TopFieldDocs.h"
#include "org/apache/lucene/store/Directory.h"
#include "org/apache/lucene/store/FSDirectory.h"
#include "org/lukhnos/lucenestudy/Document.h"
#include "org/lukhnos/lucenestudy/HighlightingHelper.h"
#include "org/lukhnos/lucenestudy/Indexer.h"
#include "org/lukhnos/lucenestudy/SearchResult.h"
#include "org/lukhnos/lucenestudy/Searcher.h"
#include "org/lukhnos/portmobile/file/Path.h"
#include "org/lukhnos/portmobile/file/Paths.h"

#if !__has_feature(objc_arc)
#error "org/lukhnos/lucenestudy/Searcher must be compiled with ARC (-fobjc-arc)"
#endif

__attribute__((unused)) static void OrgLukhnosLucenestudySearcher_SortBy_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(OrgLukhnosLucenestudySearcher_SortBy *self, OrgApacheLuceneSearchSort *sort, NSString *__name, jint __ordinal);

__attribute__((unused)) static OrgLukhnosLucenestudySearcher_SortBy *new_OrgLukhnosLucenestudySearcher_SortBy_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(OrgApacheLuceneSearchSort *sort, NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

@implementation OrgLukhnosLucenestudySearcher

- (instancetype)initWithNSString:(NSString *)indexRoot {
  OrgLukhnosLucenestudySearcher_initWithNSString_(self, indexRoot);
  return self;
}

- (OrgLukhnosLucenestudySearchResult *)searchWithNSString:(NSString *)queryStr
                                                  withInt:(jint)maxCount {
  return [self searchWithNSString:queryStr withOrgLukhnosLucenestudySearcher_SortBy:nil withInt:maxCount];
}

- (OrgLukhnosLucenestudySearchResult *)searchWithNSString:(NSString *)queryStr
                 withOrgLukhnosLucenestudySearcher_SortBy:(OrgLukhnosLucenestudySearcher_SortBy *)sortBy
                                                  withInt:(jint)maxCount {
  OrgApacheLuceneSearchQuery *query = OrgLukhnosLucenestudyIndexer_parseQueryWithOrgApacheLuceneAnalysisAnalyzer_withNSString_(analyzer_, queryStr);
  OrgApacheLuceneSearchSort *sort = nil;
  if (sortBy != nil) {
    sort = sortBy->sort_;
  }
  return [self searchAfterWithOrgApacheLuceneSearchScoreDoc:nil withOrgApacheLuceneSearchQuery:query withOrgApacheLuceneSearchSort:sort withInt:maxCount];
}

- (OrgLukhnosLucenestudySearchResult *)searchAfterWithOrgLukhnosLucenestudySearchResult:(OrgLukhnosLucenestudySearchResult *)result
                                                                                withInt:(jint)maxCount {
  if (![((OrgLukhnosLucenestudySearchResult *) nil_chk(result)) hasMore]) {
    @throw new_JavaLangAssertionError_initWithId_(@"No more search results to be fetched after this");
  }
  return [self searchAfterWithOrgApacheLuceneSearchScoreDoc:result->lastScoreDoc_ withOrgApacheLuceneSearchQuery:result->query_ withOrgApacheLuceneSearchSort:result->sort_ withInt:maxCount];
}

- (void)close {
  [((OrgApacheLuceneIndexIndexReader *) nil_chk(indexReader_)) close];
}

- (OrgLukhnosLucenestudySearchResult *)searchAfterWithOrgApacheLuceneSearchScoreDoc:(OrgApacheLuceneSearchScoreDoc *)lastScoreDoc
                                                     withOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
                                                      withOrgApacheLuceneSearchSort:(OrgApacheLuceneSearchSort *)sort
                                                                            withInt:(jint)maxCount {
  if (maxCount < 1) {
    @throw new_JavaLangAssertionError_initWithId_(JreStrcat("$I", @"maxCount must be at least 1, but instead: ", maxCount));
  }
  OrgApacheLuceneSearchIndexSearcher *searcher = new_OrgApacheLuceneSearchIndexSearcher_initWithOrgApacheLuceneIndexIndexReader_(indexReader_);
  OrgApacheLuceneSearchTopDocs *topDocs;
  jint actualMaxCount = maxCount + 1;
  if (lastScoreDoc == nil) {
    if (sort == nil) {
      topDocs = [searcher searchWithOrgApacheLuceneSearchQuery:query withInt:actualMaxCount];
    }
    else {
      topDocs = [searcher searchWithOrgApacheLuceneSearchQuery:query withInt:actualMaxCount withOrgApacheLuceneSearchSort:sort];
    }
  }
  else {
    if (sort == nil) {
      topDocs = [searcher searchAfterWithOrgApacheLuceneSearchScoreDoc:lastScoreDoc withOrgApacheLuceneSearchQuery:query withInt:actualMaxCount];
    }
    else {
      topDocs = [searcher searchAfterWithOrgApacheLuceneSearchScoreDoc:lastScoreDoc withOrgApacheLuceneSearchQuery:query withInt:actualMaxCount withOrgApacheLuceneSearchSort:sort];
    }
  }
  OrgApacheLuceneSearchScoreDoc *nextSearchAfterDoc = nil;
  jint topDocsLen;
  if (((IOSObjectArray *) nil_chk(((OrgApacheLuceneSearchTopDocs *) nil_chk(topDocs))->scoreDocs_))->size_ > maxCount) {
    nextSearchAfterDoc = IOSObjectArray_Get(topDocs->scoreDocs_, maxCount - 1);
    topDocsLen = maxCount;
  }
  else {
    topDocsLen = topDocs->scoreDocs_->size_;
  }
  OrgLukhnosLucenestudyHighlightingHelper *highlightingHelper = new_OrgLukhnosLucenestudyHighlightingHelper_initPackagePrivateWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(query, analyzer_);
  id<JavaUtilList> docs = new_JavaUtilArrayList_init();
  for (jint i = 0; i < topDocsLen; i++) {
    OrgApacheLuceneDocumentDocument *luceneDoc = [((OrgApacheLuceneIndexIndexReader *) nil_chk(indexReader_)) documentWithInt:((OrgApacheLuceneSearchScoreDoc *) nil_chk(IOSObjectArray_Get(nil_chk(topDocs->scoreDocs_), i)))->doc_];
    OrgLukhnosLucenestudyDocument *doc = OrgLukhnosLucenestudyIndexer_fromLuceneDocumentWithOrgApacheLuceneDocumentDocument_(luceneDoc);
    [docs addWithId:doc];
  }
  return new_OrgLukhnosLucenestudySearchResult_initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_(topDocs->totalHits_, docs, nextSearchAfterDoc, query, sort, highlightingHelper);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, 1, -1, -1, -1 },
    { NULL, "LOrgLukhnosLucenestudySearchResult;", 0x1, 2, 3, 4, -1, -1, -1 },
    { NULL, "LOrgLukhnosLucenestudySearchResult;", 0x1, 2, 5, 4, -1, -1, -1 },
    { NULL, "LOrgLukhnosLucenestudySearchResult;", 0x1, 6, 7, 1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 8, -1, -1, -1 },
    { NULL, "LOrgLukhnosLucenestudySearchResult;", 0x0, 6, 9, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(searchWithNSString:withInt:);
  methods[2].selector = @selector(searchWithNSString:withOrgLukhnosLucenestudySearcher_SortBy:withInt:);
  methods[3].selector = @selector(searchAfterWithOrgLukhnosLucenestudySearchResult:withInt:);
  methods[4].selector = @selector(close);
  methods[5].selector = @selector(searchAfterWithOrgApacheLuceneSearchScoreDoc:withOrgApacheLuceneSearchQuery:withOrgApacheLuceneSearchSort:withInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "analyzer_", "LOrgApacheLuceneAnalysisAnalyzer;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "indexReader_", "LOrgApacheLuceneIndexIndexReader;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "LJavaIoIOException;", "search", "LNSString;I", "LOrgApacheLuceneQueryparserClassicParseException;LJavaIoIOException;", "LNSString;LOrgLukhnosLucenestudySearcher_SortBy;I", "searchAfter", "LOrgLukhnosLucenestudySearchResult;I", "LJavaLangException;", "LOrgApacheLuceneSearchScoreDoc;LOrgApacheLuceneSearchQuery;LOrgApacheLuceneSearchSort;I", "LOrgLukhnosLucenestudySearcher_SortBy;" };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudySearcher = { "Searcher", "org.lukhnos.lucenestudy", ptrTable, methods, fields, 7, 0x1, 6, 2, -1, 10, -1, -1, -1 };
  return &_OrgLukhnosLucenestudySearcher;
}

@end

void OrgLukhnosLucenestudySearcher_initWithNSString_(OrgLukhnosLucenestudySearcher *self, NSString *indexRoot) {
  NSObject_init(self);
  OrgLukhnosPortmobileFilePath *indexRootPath = OrgLukhnosPortmobileFilePaths_getWithNSString_(indexRoot);
  self->analyzer_ = OrgLukhnosLucenestudyIndexer_getAnalyzer();
  OrgApacheLuceneStoreDirectory *mainIndexDir = OrgApacheLuceneStoreFSDirectory_openWithOrgLukhnosPortmobileFilePath_(OrgLukhnosLucenestudyIndexer_getMainIndexPathWithOrgLukhnosPortmobileFilePath_(indexRootPath));
  self->indexReader_ = OrgApacheLuceneIndexDirectoryReader_openWithOrgApacheLuceneStoreDirectory_(mainIndexDir);
}

OrgLukhnosLucenestudySearcher *new_OrgLukhnosLucenestudySearcher_initWithNSString_(NSString *indexRoot) {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudySearcher, initWithNSString_, indexRoot)
}

OrgLukhnosLucenestudySearcher *create_OrgLukhnosLucenestudySearcher_initWithNSString_(NSString *indexRoot) {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudySearcher, initWithNSString_, indexRoot)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudySearcher)

J2OBJC_INITIALIZED_DEFN(OrgLukhnosLucenestudySearcher_SortBy)

OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_values_[5];

@implementation OrgLukhnosLucenestudySearcher_SortBy

+ (IOSObjectArray *)values {
  return OrgLukhnosLucenestudySearcher_SortBy_values();
}

+ (OrgLukhnosLucenestudySearcher_SortBy *)valueOfWithNSString:(NSString *)name {
  return OrgLukhnosLucenestudySearcher_SortBy_valueOfWithNSString_(name);
}

- (OrgLukhnosLucenestudySearcher_SortBy_Enum)toNSEnum {
  return (OrgLukhnosLucenestudySearcher_SortBy_Enum)[self ordinal];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LOrgLukhnosLucenestudySearcher_SortBy;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgLukhnosLucenestudySearcher_SortBy;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "RELEVANCE", "LOrgLukhnosLucenestudySearcher_SortBy;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "DOCUMENT_ORDER", "LOrgLukhnosLucenestudySearcher_SortBy;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "TITLE", "LOrgLukhnosLucenestudySearcher_SortBy;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "YEAR", "LOrgLukhnosLucenestudySearcher_SortBy;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "RATING", "LOrgLukhnosLucenestudySearcher_SortBy;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "sort_", "LOrgApacheLuceneSearchSort;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(OrgLukhnosLucenestudySearcher_SortBy, RELEVANCE), &JreEnum(OrgLukhnosLucenestudySearcher_SortBy, DOCUMENT_ORDER), &JreEnum(OrgLukhnosLucenestudySearcher_SortBy, TITLE), &JreEnum(OrgLukhnosLucenestudySearcher_SortBy, YEAR), &JreEnum(OrgLukhnosLucenestudySearcher_SortBy, RATING), "LOrgLukhnosLucenestudySearcher;", "Ljava/lang/Enum<Lorg/lukhnos/lucenestudy/Searcher$SortBy;>;" };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudySearcher_SortBy = { "SortBy", "org.lukhnos.lucenestudy", ptrTable, methods, fields, 7, 0x4019, 2, 6, 7, -1, -1, 8, -1 };
  return &_OrgLukhnosLucenestudySearcher_SortBy;
}

+ (void)initialize {
  if (self == [OrgLukhnosLucenestudySearcher_SortBy class]) {
    JreEnum(OrgLukhnosLucenestudySearcher_SortBy, RELEVANCE) = new_OrgLukhnosLucenestudySearcher_SortBy_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(JreLoadStatic(OrgApacheLuceneSearchSort, RELEVANCE), @"RELEVANCE", 0);
    JreEnum(OrgLukhnosLucenestudySearcher_SortBy, DOCUMENT_ORDER) = new_OrgLukhnosLucenestudySearcher_SortBy_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(JreLoadStatic(OrgApacheLuceneSearchSort, INDEXORDER), @"DOCUMENT_ORDER", 1);
    JreEnum(OrgLukhnosLucenestudySearcher_SortBy, TITLE) = new_OrgLukhnosLucenestudySearcher_SortBy_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(new_OrgApacheLuceneSearchSort_initWithOrgApacheLuceneSearchSortField_(new_OrgApacheLuceneSearchSortField_initWithNSString_withOrgApacheLuceneSearchSortField_Type_(OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME, JreLoadEnum(OrgApacheLuceneSearchSortField_Type, STRING))), @"TITLE", 2);
    JreEnum(OrgLukhnosLucenestudySearcher_SortBy, YEAR) = new_OrgLukhnosLucenestudySearcher_SortBy_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(new_OrgApacheLuceneSearchSort_initWithOrgApacheLuceneSearchSortField_(new_OrgApacheLuceneSearchSortField_initWithNSString_withOrgApacheLuceneSearchSortField_Type_withBoolean_(OrgLukhnosLucenestudyIndexer_YEAR_FIELD_NAME, JreLoadEnum(OrgApacheLuceneSearchSortField_Type, INT), true)), @"YEAR", 3);
    JreEnum(OrgLukhnosLucenestudySearcher_SortBy, RATING) = new_OrgLukhnosLucenestudySearcher_SortBy_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(new_OrgApacheLuceneSearchSort_initWithOrgApacheLuceneSearchSortField_(new_OrgApacheLuceneSearchSortField_initWithNSString_withOrgApacheLuceneSearchSortField_Type_withBoolean_(OrgLukhnosLucenestudyIndexer_RATING_FIELD_NAME, JreLoadEnum(OrgApacheLuceneSearchSortField_Type, INT), true)), @"RATING", 4);
    J2OBJC_SET_INITIALIZED(OrgLukhnosLucenestudySearcher_SortBy)
  }
}

@end

void OrgLukhnosLucenestudySearcher_SortBy_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(OrgLukhnosLucenestudySearcher_SortBy *self, OrgApacheLuceneSearchSort *sort, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  self->sort_ = sort;
}

OrgLukhnosLucenestudySearcher_SortBy *new_OrgLukhnosLucenestudySearcher_SortBy_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(OrgApacheLuceneSearchSort *sort, NSString *__name, jint __ordinal) {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudySearcher_SortBy, initWithOrgApacheLuceneSearchSort_withNSString_withInt_, sort, __name, __ordinal)
}

IOSObjectArray *OrgLukhnosLucenestudySearcher_SortBy_values() {
  OrgLukhnosLucenestudySearcher_SortBy_initialize();
  return [IOSObjectArray arrayWithObjects:OrgLukhnosLucenestudySearcher_SortBy_values_ count:5 type:OrgLukhnosLucenestudySearcher_SortBy_class_()];
}

OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_valueOfWithNSString_(NSString *name) {
  OrgLukhnosLucenestudySearcher_SortBy_initialize();
  for (int i = 0; i < 5; i++) {
    OrgLukhnosLucenestudySearcher_SortBy *e = OrgLukhnosLucenestudySearcher_SortBy_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

OrgLukhnosLucenestudySearcher_SortBy *OrgLukhnosLucenestudySearcher_SortBy_fromOrdinal(NSUInteger ordinal) {
  OrgLukhnosLucenestudySearcher_SortBy_initialize();
  if (ordinal >= 5) {
    return nil;
  }
  return OrgLukhnosLucenestudySearcher_SortBy_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudySearcher_SortBy)
