//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/SearchResult.java
//

#include "J2ObjC_source.h"
#include "java/lang/Integer.h"
#include "java/util/List.h"
#include "org/apache/lucene/search/Query.h"
#include "org/apache/lucene/search/ScoreDoc.h"
#include "org/apache/lucene/search/Sort.h"
#include "org/lukhnos/lucenestudy/Document.h"
#include "org/lukhnos/lucenestudy/HighlightingHelper.h"
#include "org/lukhnos/lucenestudy/Indexer.h"
#include "org/lukhnos/lucenestudy/SearchResult.h"

#if !__has_feature(objc_arc)
#error "org/lukhnos/lucenestudy/SearchResult must be compiled with ARC (-fobjc-arc)"
#endif

@implementation OrgLukhnosLucenestudySearchResult

- (instancetype)initWithInt:(jint)totalHits
           withJavaUtilList:(id<JavaUtilList>)documents
withOrgApacheLuceneSearchScoreDoc:(OrgApacheLuceneSearchScoreDoc *)lastScoreDoc
withOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
withOrgApacheLuceneSearchSort:(OrgApacheLuceneSearchSort *)sort
withOrgLukhnosLucenestudyHighlightingHelper:(OrgLukhnosLucenestudyHighlightingHelper *)highlightingHelper {
  OrgLukhnosLucenestudySearchResult_initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_(self, totalHits, documents, lastScoreDoc, query, sort, highlightingHelper);
  return self;
}

- (jboolean)hasMore {
  return lastScoreDoc_ != nil;
}

- (NSString *)getHighlightedTitleWithOrgLukhnosLucenestudyDocument:(OrgLukhnosLucenestudyDocument *)doc {
  [((OrgLukhnosLucenestudyHighlightingHelper *) nil_chk(highlightingHelper_)) setFragmentLengthWithInt:JavaLangInteger_MAX_VALUE];
  [highlightingHelper_ setLineFeedHTMLEscapeWithBoolean:false];
  return [highlightingHelper_ highlightOrOriginalWithNSString:OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME withNSString:((OrgLukhnosLucenestudyDocument *) nil_chk(doc))->title_];
}

- (NSString *)getHighlightedReviewWithOrgLukhnosLucenestudyDocument:(OrgLukhnosLucenestudyDocument *)doc {
  [((OrgLukhnosLucenestudyHighlightingHelper *) nil_chk(highlightingHelper_)) setFragmentLengthWithInt:OrgLukhnosLucenestudyHighlightingHelper_DEFAULT_FRAGMENT_LENGTH];
  [highlightingHelper_ setLineFeedHTMLEscapeWithBoolean:false];
  return [highlightingHelper_ highlightOrOriginalWithNSString:OrgLukhnosLucenestudyIndexer_REVIEW_FIELD_NAME withNSString:((OrgLukhnosLucenestudyDocument *) nil_chk(doc))->review_];
}

- (NSString *)getFullHighlightedReviewWithOrgLukhnosLucenestudyDocument:(OrgLukhnosLucenestudyDocument *)doc {
  [((OrgLukhnosLucenestudyHighlightingHelper *) nil_chk(highlightingHelper_)) setFragmentLengthWithInt:JavaLangInteger_MAX_VALUE];
  [highlightingHelper_ setLineFeedHTMLEscapeWithBoolean:true];
  return [highlightingHelper_ highlightOrOriginalWithNSString:OrgLukhnosLucenestudyIndexer_REVIEW_FIELD_NAME withNSString:((OrgLukhnosLucenestudyDocument *) nil_chk(doc))->review_];
}

- (void)setFragmentLengthWithInt:(jint)length {
  fragmentLength_ = length;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, 1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 4, 3, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 5, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithInt:withJavaUtilList:withOrgApacheLuceneSearchScoreDoc:withOrgApacheLuceneSearchQuery:withOrgApacheLuceneSearchSort:withOrgLukhnosLucenestudyHighlightingHelper:);
  methods[1].selector = @selector(hasMore);
  methods[2].selector = @selector(getHighlightedTitleWithOrgLukhnosLucenestudyDocument:);
  methods[3].selector = @selector(getHighlightedReviewWithOrgLukhnosLucenestudyDocument:);
  methods[4].selector = @selector(getFullHighlightedReviewWithOrgLukhnosLucenestudyDocument:);
  methods[5].selector = @selector(setFragmentLengthWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "totalHits_", "I", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "documents_", "LJavaUtilList;", .constantValue.asLong = 0, 0x11, -1, -1, 8, -1 },
    { "lastScoreDoc_", "LOrgApacheLuceneSearchScoreDoc;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "query_", "LOrgApacheLuceneSearchQuery;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "sort_", "LOrgApacheLuceneSearchSort;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "highlightingHelper_", "LOrgLukhnosLucenestudyHighlightingHelper;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "fragmentLength_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "ILJavaUtilList;LOrgApacheLuceneSearchScoreDoc;LOrgApacheLuceneSearchQuery;LOrgApacheLuceneSearchSort;LOrgLukhnosLucenestudyHighlightingHelper;", "(ILjava/util/List<Lorg/lukhnos/lucenestudy/Document;>;Lorg/apache/lucene/search/ScoreDoc;Lorg/apache/lucene/search/Query;Lorg/apache/lucene/search/Sort;Lorg/lukhnos/lucenestudy/HighlightingHelper;)V", "getHighlightedTitle", "LOrgLukhnosLucenestudyDocument;", "getHighlightedReview", "getFullHighlightedReview", "setFragmentLength", "I", "Ljava/util/List<Lorg/lukhnos/lucenestudy/Document;>;" };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudySearchResult = { "SearchResult", "org.lukhnos.lucenestudy", ptrTable, methods, fields, 7, 0x1, 6, 7, -1, -1, -1, -1, -1 };
  return &_OrgLukhnosLucenestudySearchResult;
}

@end

void OrgLukhnosLucenestudySearchResult_initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_(OrgLukhnosLucenestudySearchResult *self, jint totalHits, id<JavaUtilList> documents, OrgApacheLuceneSearchScoreDoc *lastScoreDoc, OrgApacheLuceneSearchQuery *query, OrgApacheLuceneSearchSort *sort, OrgLukhnosLucenestudyHighlightingHelper *highlightingHelper) {
  NSObject_init(self);
  self->fragmentLength_ = OrgLukhnosLucenestudyHighlightingHelper_DEFAULT_FRAGMENT_LENGTH;
  self->totalHits_ = totalHits;
  self->documents_ = documents;
  self->lastScoreDoc_ = lastScoreDoc;
  self->query_ = query;
  self->sort_ = sort;
  self->highlightingHelper_ = highlightingHelper;
}

OrgLukhnosLucenestudySearchResult *new_OrgLukhnosLucenestudySearchResult_initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_(jint totalHits, id<JavaUtilList> documents, OrgApacheLuceneSearchScoreDoc *lastScoreDoc, OrgApacheLuceneSearchQuery *query, OrgApacheLuceneSearchSort *sort, OrgLukhnosLucenestudyHighlightingHelper *highlightingHelper) {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudySearchResult, initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_, totalHits, documents, lastScoreDoc, query, sort, highlightingHelper)
}

OrgLukhnosLucenestudySearchResult *create_OrgLukhnosLucenestudySearchResult_initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_(jint totalHits, id<JavaUtilList> documents, OrgApacheLuceneSearchScoreDoc *lastScoreDoc, OrgApacheLuceneSearchQuery *query, OrgApacheLuceneSearchSort *sort, OrgLukhnosLucenestudyHighlightingHelper *highlightingHelper) {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudySearchResult, initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_, totalHits, documents, lastScoreDoc, query, sort, highlightingHelper)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudySearchResult)
