//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Searcher.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/io/IOException.h"
#include "java/lang/AssertionError.h"
#include "java/lang/Enum.h"
#include "java/lang/Exception.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"
#include "org/apache/lucene/analysis/Analyzer.h"
#include "org/apache/lucene/document/Document.h"
#include "org/apache/lucene/index/DirectoryReader.h"
#include "org/apache/lucene/index/IndexReader.h"
#include "org/apache/lucene/queryparser/classic/MultiFieldQueryParser.h"
#include "org/apache/lucene/queryparser/classic/ParseException.h"
#include "org/apache/lucene/queryparser/classic/QueryParser.h"
#include "org/apache/lucene/search/IndexSearcher.h"
#include "org/apache/lucene/search/Query.h"
#include "org/apache/lucene/search/ScoreDoc.h"
#include "org/apache/lucene/search/Sort.h"
#include "org/apache/lucene/search/SortField.h"
#include "org/apache/lucene/search/TopDocs.h"
#include "org/apache/lucene/search/TopFieldDocs.h"
#include "org/apache/lucene/store/Directory.h"
#include "org/apache/lucene/store/FSDirectory.h"
#include "org/lukhnos/lucenestudy/Document.h"
#include "org/lukhnos/lucenestudy/HighlightingHelper.h"
#include "org/lukhnos/lucenestudy/Indexer.h"
#include "org/lukhnos/lucenestudy/SearchResult.h"
#include "org/lukhnos/lucenestudy/Searcher.h"
#include "org/lukhnos/portmobile/file/Path.h"
#include "org/lukhnos/portmobile/file/Paths.h"

__attribute__((unused)) static void OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(OrgLukhnosLucenestudySearcher_SortByEnum *self, OrgApacheLuceneSearchSort *sort, NSString *__name, jint __ordinal);

__attribute__((unused)) static OrgLukhnosLucenestudySearcher_SortByEnum *new_OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(OrgApacheLuceneSearchSort *sort, NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

@implementation OrgLukhnosLucenestudySearcher

- (instancetype)initWithNSString:(NSString *)indexRoot {
  OrgLukhnosLucenestudySearcher_initWithNSString_(self, indexRoot);
  return self;
}

- (OrgLukhnosLucenestudySearchResult *)searchWithNSString:(NSString *)queryStr
                                                  withInt:(jint)maxCount {
  return [self searchWithNSString:queryStr withOrgLukhnosLucenestudySearcher_SortByEnum:nil withInt:maxCount];
}

- (OrgLukhnosLucenestudySearchResult *)searchWithNSString:(NSString *)queryStr
             withOrgLukhnosLucenestudySearcher_SortByEnum:(OrgLukhnosLucenestudySearcher_SortByEnum *)sortBy
                                                  withInt:(jint)maxCount {
  IOSObjectArray *fields = [IOSObjectArray newArrayWithObjects:(id[]){ OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME_, OrgLukhnosLucenestudyIndexer_REVIEW_FIELD_NAME_ } count:2 type:NSString_class_()];
  OrgApacheLuceneQueryparserClassicQueryParser *parser = new_OrgApacheLuceneQueryparserClassicMultiFieldQueryParser_initWithNSStringArray_withOrgApacheLuceneAnalysisAnalyzer_(fields, analyzer_);
  OrgApacheLuceneSearchQuery *query = [parser parseWithNSString:queryStr];
  OrgApacheLuceneSearchSort *sort = nil;
  if (sortBy != nil) {
    sort = sortBy->sort_;
  }
  return [self searchAfterWithOrgApacheLuceneSearchScoreDoc:nil withOrgApacheLuceneSearchQuery:query withOrgApacheLuceneSearchSort:sort withInt:maxCount];
}

- (OrgLukhnosLucenestudySearchResult *)searchAfterWithOrgLukhnosLucenestudySearchResult:(OrgLukhnosLucenestudySearchResult *)result
                                                                                withInt:(jint)maxCount {
  if (![((OrgLukhnosLucenestudySearchResult *) nil_chk(result)) hasMore]) {
    @throw new_JavaLangAssertionError_initWithId_(@"No more search results to be fetched after this");
  }
  return [self searchAfterWithOrgApacheLuceneSearchScoreDoc:result->lastScoreDoc_ withOrgApacheLuceneSearchQuery:result->query_ withOrgApacheLuceneSearchSort:result->sort_ withInt:maxCount];
}

- (void)close {
  [((OrgApacheLuceneIndexIndexReader *) nil_chk(indexReader_)) close];
}

- (OrgLukhnosLucenestudySearchResult *)searchAfterWithOrgApacheLuceneSearchScoreDoc:(OrgApacheLuceneSearchScoreDoc *)lastScoreDoc
                                                     withOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
                                                      withOrgApacheLuceneSearchSort:(OrgApacheLuceneSearchSort *)sort
                                                                            withInt:(jint)maxCount {
  if (maxCount < 1) {
    @throw new_JavaLangAssertionError_initWithId_(JreStrcat("$I", @"maxCount must be at least 1, but instead: ", maxCount));
  }
  OrgApacheLuceneSearchIndexSearcher *searcher = new_OrgApacheLuceneSearchIndexSearcher_initWithOrgApacheLuceneIndexIndexReader_(indexReader_);
  OrgApacheLuceneSearchTopDocs *topDocs;
  jint actualMaxCount = maxCount + 1;
  if (lastScoreDoc == nil) {
    if (sort == nil) {
      topDocs = [searcher searchWithOrgApacheLuceneSearchQuery:query withInt:actualMaxCount];
    }
    else {
      topDocs = [searcher searchWithOrgApacheLuceneSearchQuery:query withInt:actualMaxCount withOrgApacheLuceneSearchSort:sort];
    }
  }
  else {
    if (sort == nil) {
      topDocs = [searcher searchAfterWithOrgApacheLuceneSearchScoreDoc:lastScoreDoc withOrgApacheLuceneSearchQuery:query withInt:actualMaxCount];
    }
    else {
      topDocs = [searcher searchAfterWithOrgApacheLuceneSearchScoreDoc:lastScoreDoc withOrgApacheLuceneSearchQuery:query withInt:actualMaxCount withOrgApacheLuceneSearchSort:sort];
    }
  }
  OrgApacheLuceneSearchScoreDoc *nextSearchAfterDoc = nil;
  jint topDocsLen;
  if (((IOSObjectArray *) nil_chk(((OrgApacheLuceneSearchTopDocs *) nil_chk(topDocs))->scoreDocs_))->size_ > maxCount) {
    nextSearchAfterDoc = IOSObjectArray_Get(topDocs->scoreDocs_, maxCount - 1);
    topDocsLen = maxCount;
  }
  else {
    topDocsLen = topDocs->scoreDocs_->size_;
  }
  OrgLukhnosLucenestudyHighlightingHelper *highlightingHelper = new_OrgLukhnosLucenestudyHighlightingHelper_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneAnalysisAnalyzer_(query, analyzer_);
  id<JavaUtilList> docs = new_JavaUtilArrayList_init();
  for (jint i = 0; i < topDocsLen; i++) {
    OrgApacheLuceneDocumentDocument *luceneDoc = [((OrgApacheLuceneIndexIndexReader *) nil_chk(indexReader_)) documentWithInt:((OrgApacheLuceneSearchScoreDoc *) nil_chk(IOSObjectArray_Get(topDocs->scoreDocs_, i)))->doc_];
    OrgLukhnosLucenestudyDocument *doc = OrgLukhnosLucenestudyIndexer_fromLuceneDocumentWithOrgApacheLuceneDocumentDocument_(luceneDoc);
    [docs addWithId:doc];
  }
  return new_OrgLukhnosLucenestudySearchResult_initWithInt_withJavaUtilList_withOrgApacheLuceneSearchScoreDoc_withOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchSort_withOrgLukhnosLucenestudyHighlightingHelper_(topDocs->totalHits_, docs, nextSearchAfterDoc, query, sort, highlightingHelper);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "Searcher", NULL, 0x1, "Ljava.io.IOException;", NULL },
    { "searchWithNSString:withInt:", "search", "Lorg.lukhnos.lucenestudy.SearchResult;", 0x1, "Lorg.apache.lucene.queryparser.classic.ParseException;Ljava.io.IOException;", NULL },
    { "searchWithNSString:withOrgLukhnosLucenestudySearcher_SortByEnum:withInt:", "search", "Lorg.lukhnos.lucenestudy.SearchResult;", 0x1, "Lorg.apache.lucene.queryparser.classic.ParseException;Ljava.io.IOException;", NULL },
    { "searchAfterWithOrgLukhnosLucenestudySearchResult:withInt:", "searchAfter", "Lorg.lukhnos.lucenestudy.SearchResult;", 0x1, "Ljava.io.IOException;", NULL },
    { "close", NULL, "V", 0x1, "Ljava.lang.Exception;", NULL },
    { "searchAfterWithOrgApacheLuceneSearchScoreDoc:withOrgApacheLuceneSearchQuery:withOrgApacheLuceneSearchSort:withInt:", "searchAfter", "Lorg.lukhnos.lucenestudy.SearchResult;", 0x0, "Ljava.io.IOException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "analyzer_", NULL, 0x10, "Lorg.apache.lucene.analysis.Analyzer;", NULL, NULL, .constantValue.asLong = 0 },
    { "indexReader_", NULL, 0x10, "Lorg.apache.lucene.index.IndexReader;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *inner_classes[] = {"Lorg.lukhnos.lucenestudy.Searcher$SortBy;"};
  static const J2ObjcClassInfo _OrgLukhnosLucenestudySearcher = { 2, "Searcher", "org.lukhnos.lucenestudy", NULL, 0x1, 6, methods, 2, fields, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_OrgLukhnosLucenestudySearcher;
}

@end

void OrgLukhnosLucenestudySearcher_initWithNSString_(OrgLukhnosLucenestudySearcher *self, NSString *indexRoot) {
  (void) NSObject_init(self);
  OrgLukhnosPortmobileFilePath *indexRootPath = OrgLukhnosPortmobileFilePaths_getWithNSString_(indexRoot);
  self->analyzer_ = OrgLukhnosLucenestudyIndexer_getAnalyzer();
  OrgApacheLuceneStoreDirectory *mainIndexDir = OrgApacheLuceneStoreFSDirectory_openWithOrgLukhnosPortmobileFilePath_(OrgLukhnosLucenestudyIndexer_getMainIndexPathWithOrgLukhnosPortmobileFilePath_(indexRootPath));
  self->indexReader_ = OrgApacheLuceneIndexDirectoryReader_openWithOrgApacheLuceneStoreDirectory_(mainIndexDir);
}

OrgLukhnosLucenestudySearcher *new_OrgLukhnosLucenestudySearcher_initWithNSString_(NSString *indexRoot) {
  OrgLukhnosLucenestudySearcher *self = [OrgLukhnosLucenestudySearcher alloc];
  OrgLukhnosLucenestudySearcher_initWithNSString_(self, indexRoot);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudySearcher)

J2OBJC_INITIALIZED_DEFN(OrgLukhnosLucenestudySearcher_SortByEnum)

OrgLukhnosLucenestudySearcher_SortByEnum *OrgLukhnosLucenestudySearcher_SortByEnum_values_[5];

@implementation OrgLukhnosLucenestudySearcher_SortByEnum

- (instancetype)initWithOrgApacheLuceneSearchSort:(OrgApacheLuceneSearchSort *)sort
                                     withNSString:(NSString *)__name
                                          withInt:(jint)__ordinal {
  OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(self, sort, __name, __ordinal);
  return self;
}

IOSObjectArray *OrgLukhnosLucenestudySearcher_SortByEnum_values() {
  OrgLukhnosLucenestudySearcher_SortByEnum_initialize();
  return [IOSObjectArray arrayWithObjects:OrgLukhnosLucenestudySearcher_SortByEnum_values_ count:5 type:OrgLukhnosLucenestudySearcher_SortByEnum_class_()];
}

+ (IOSObjectArray *)values {
  return OrgLukhnosLucenestudySearcher_SortByEnum_values();
}

+ (OrgLukhnosLucenestudySearcher_SortByEnum *)valueOfWithNSString:(NSString *)name {
  return OrgLukhnosLucenestudySearcher_SortByEnum_valueOfWithNSString_(name);
}

OrgLukhnosLucenestudySearcher_SortByEnum *OrgLukhnosLucenestudySearcher_SortByEnum_valueOfWithNSString_(NSString *name) {
  OrgLukhnosLucenestudySearcher_SortByEnum_initialize();
  for (int i = 0; i < 5; i++) {
    OrgLukhnosLucenestudySearcher_SortByEnum *e = OrgLukhnosLucenestudySearcher_SortByEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (void)initialize {
  if (self == [OrgLukhnosLucenestudySearcher_SortByEnum class]) {
    OrgLukhnosLucenestudySearcher_SortByEnum_RELEVANCE = new_OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(JreLoadStatic(OrgApacheLuceneSearchSort, RELEVANCE_), @"RELEVANCE", 0);
    OrgLukhnosLucenestudySearcher_SortByEnum_DOCUMENT_ORDER = new_OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(JreLoadStatic(OrgApacheLuceneSearchSort, INDEXORDER_), @"DOCUMENT_ORDER", 1);
    OrgLukhnosLucenestudySearcher_SortByEnum_TITLE = new_OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(new_OrgApacheLuceneSearchSort_initWithOrgApacheLuceneSearchSortField_(new_OrgApacheLuceneSearchSortField_initWithNSString_withOrgApacheLuceneSearchSortField_TypeEnum_(OrgLukhnosLucenestudyIndexer_TITLE_FIELD_NAME_, JreLoadStatic(OrgApacheLuceneSearchSortField_TypeEnum, STRING))), @"TITLE", 2);
    OrgLukhnosLucenestudySearcher_SortByEnum_YEAR = new_OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(new_OrgApacheLuceneSearchSort_initWithOrgApacheLuceneSearchSortField_(new_OrgApacheLuceneSearchSortField_initWithNSString_withOrgApacheLuceneSearchSortField_TypeEnum_withBoolean_(OrgLukhnosLucenestudyIndexer_YEAR_FIELD_NAME_, JreLoadStatic(OrgApacheLuceneSearchSortField_TypeEnum, INT), YES)), @"YEAR", 3);
    OrgLukhnosLucenestudySearcher_SortByEnum_RATING = new_OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(new_OrgApacheLuceneSearchSort_initWithOrgApacheLuceneSearchSortField_(new_OrgApacheLuceneSearchSortField_initWithNSString_withOrgApacheLuceneSearchSortField_TypeEnum_withBoolean_(OrgLukhnosLucenestudyIndexer_RATING_FIELD_NAME_, JreLoadStatic(OrgApacheLuceneSearchSortField_TypeEnum, INT), YES)), @"RATING", 4);
    J2OBJC_SET_INITIALIZED(OrgLukhnosLucenestudySearcher_SortByEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "RELEVANCE", "RELEVANCE", 0x4019, "Lorg.lukhnos.lucenestudy.Searcher$SortBy;", &OrgLukhnosLucenestudySearcher_SortByEnum_RELEVANCE, NULL, .constantValue.asLong = 0 },
    { "DOCUMENT_ORDER", "DOCUMENT_ORDER", 0x4019, "Lorg.lukhnos.lucenestudy.Searcher$SortBy;", &OrgLukhnosLucenestudySearcher_SortByEnum_DOCUMENT_ORDER, NULL, .constantValue.asLong = 0 },
    { "TITLE", "TITLE", 0x4019, "Lorg.lukhnos.lucenestudy.Searcher$SortBy;", &OrgLukhnosLucenestudySearcher_SortByEnum_TITLE, NULL, .constantValue.asLong = 0 },
    { "YEAR", "YEAR", 0x4019, "Lorg.lukhnos.lucenestudy.Searcher$SortBy;", &OrgLukhnosLucenestudySearcher_SortByEnum_YEAR, NULL, .constantValue.asLong = 0 },
    { "RATING", "RATING", 0x4019, "Lorg.lukhnos.lucenestudy.Searcher$SortBy;", &OrgLukhnosLucenestudySearcher_SortByEnum_RATING, NULL, .constantValue.asLong = 0 },
    { "sort_", NULL, 0x10, "Lorg.apache.lucene.search.Sort;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lorg.lukhnos.lucenestudy.Searcher$SortBy;"};
  static const J2ObjcClassInfo _OrgLukhnosLucenestudySearcher_SortByEnum = { 2, "SortBy", "org.lukhnos.lucenestudy", "Searcher", 0x4019, 0, NULL, 6, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lorg/lukhnos/lucenestudy/Searcher$SortBy;>;" };
  return &_OrgLukhnosLucenestudySearcher_SortByEnum;
}

@end

void OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(OrgLukhnosLucenestudySearcher_SortByEnum *self, OrgApacheLuceneSearchSort *sort, NSString *__name, jint __ordinal) {
  (void) JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  self->sort_ = sort;
}

OrgLukhnosLucenestudySearcher_SortByEnum *new_OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(OrgApacheLuceneSearchSort *sort, NSString *__name, jint __ordinal) {
  OrgLukhnosLucenestudySearcher_SortByEnum *self = [OrgLukhnosLucenestudySearcher_SortByEnum alloc];
  OrgLukhnosLucenestudySearcher_SortByEnum_initWithOrgApacheLuceneSearchSort_withNSString_withInt_(self, sort, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudySearcher_SortByEnum)
