//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Study.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgLukhnosLucenestudyStudy")
#ifdef RESTRICT_OrgLukhnosLucenestudyStudy
#define INCLUDE_ALL_OrgLukhnosLucenestudyStudy 0
#else
#define INCLUDE_ALL_OrgLukhnosLucenestudyStudy 1
#endif
#undef RESTRICT_OrgLukhnosLucenestudyStudy

#if !defined (OrgLukhnosLucenestudyStudy_) && (INCLUDE_ALL_OrgLukhnosLucenestudyStudy || defined(INCLUDE_OrgLukhnosLucenestudyStudy))
#define OrgLukhnosLucenestudyStudy_

@class IOSObjectArray;
@class JavaIoInputStream;

@interface OrgLukhnosLucenestudyStudy : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)importDataWithJavaIoInputStream:(JavaIoInputStream *)stream
                           withNSString:(NSString *)indexPath
                            withBoolean:(jboolean)withSuggestion;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

#pragma mark Package-Private

+ (void)addWithNSString:(NSString *)indexPath
           withNSString:(NSString *)title
           withNSString:(NSString *)year
           withNSString:(NSString *)rating
           withNSString:(NSString *)positive
           withNSString:(NSString *)review
           withNSString:(NSString *)source;

+ (void)delete__WithNSString:(NSString *)indexPath
                withNSString:(NSString *)query;

+ (void)indexWithNSString:(NSString *)sourcePath
             withNSString:(NSString *)indexPath;

+ (void)searchWithNSString:(NSString *)indexPath
              withNSString:(NSString *)query;

+ (void)showHelpAndExit;

+ (void)suggestWithNSString:(NSString *)indexPath
               withNSString:(NSString *)query;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudyStudy)

FOUNDATION_EXPORT void OrgLukhnosLucenestudyStudy_mainWithNSStringArray_(IOSObjectArray *args);

FOUNDATION_EXPORT void OrgLukhnosLucenestudyStudy_showHelpAndExit();

FOUNDATION_EXPORT void OrgLukhnosLucenestudyStudy_indexWithNSString_withNSString_(NSString *sourcePath, NSString *indexPath);

FOUNDATION_EXPORT jint OrgLukhnosLucenestudyStudy_importDataWithJavaIoInputStream_withNSString_withBoolean_(JavaIoInputStream *stream, NSString *indexPath, jboolean withSuggestion);

FOUNDATION_EXPORT void OrgLukhnosLucenestudyStudy_searchWithNSString_withNSString_(NSString *indexPath, NSString *query);

FOUNDATION_EXPORT void OrgLukhnosLucenestudyStudy_delete__WithNSString_withNSString_(NSString *indexPath, NSString *query);

FOUNDATION_EXPORT void OrgLukhnosLucenestudyStudy_suggestWithNSString_withNSString_(NSString *indexPath, NSString *query);

FOUNDATION_EXPORT void OrgLukhnosLucenestudyStudy_addWithNSString_withNSString_withNSString_withNSString_withNSString_withNSString_withNSString_(NSString *indexPath, NSString *title, NSString *year, NSString *rating, NSString *positive, NSString *review, NSString *source);

FOUNDATION_EXPORT void OrgLukhnosLucenestudyStudy_init(OrgLukhnosLucenestudyStudy *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudyStudy *new_OrgLukhnosLucenestudyStudy_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgLukhnosLucenestudyStudy *create_OrgLukhnosLucenestudyStudy_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyStudy)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgLukhnosLucenestudyStudy")
