//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Suggester.java
//

#ifndef _OrgLukhnosLucenestudySuggester_H_
#define _OrgLukhnosLucenestudySuggester_H_

#include "J2ObjC_header.h"
#include "java/lang/AutoCloseable.h"

@class OrgApacheLuceneSearchSuggestAnalyzingAnalyzingInfixSuggester;
@class OrgLukhnosPortmobileFilePath;
@protocol JavaUtilList;

#define OrgLukhnosLucenestudySuggester_DEFAULT_SUGGESTION_COUNT 10

@interface OrgLukhnosLucenestudySuggester : NSObject < JavaLangAutoCloseable > {
 @public
  OrgLukhnosPortmobileFilePath *indexRootPath_;
  OrgApacheLuceneSearchSuggestAnalyzingAnalyzingInfixSuggester *suggester_;
  jint suggestionCount_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)indexRoot;

- (void)close;

+ (void)rebuildWithNSString:(NSString *)indexRoot;

- (id<JavaUtilList>)suggestWithNSString:(NSString *)query;

#pragma mark Package-Private

+ (OrgLukhnosPortmobileFilePath *)getSuggestionIndexPathWithOrgLukhnosPortmobileFilePath:(OrgLukhnosPortmobileFilePath *)indexRoot;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudySuggester)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySuggester, indexRootPath_, OrgLukhnosPortmobileFilePath *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySuggester, suggester_, OrgApacheLuceneSearchSuggestAnalyzingAnalyzingInfixSuggester *)

J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudySuggester, DEFAULT_SUGGESTION_COUNT, jint)

FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudySuggester_INDEX_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgLukhnosLucenestudySuggester, INDEX_NAME_, NSString *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudySuggester_initWithNSString_(OrgLukhnosLucenestudySuggester *self, NSString *indexRoot);

FOUNDATION_EXPORT OrgLukhnosLucenestudySuggester *new_OrgLukhnosLucenestudySuggester_initWithNSString_(NSString *indexRoot) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgLukhnosPortmobileFilePath *OrgLukhnosLucenestudySuggester_getSuggestionIndexPathWithOrgLukhnosPortmobileFilePath_(OrgLukhnosPortmobileFilePath *indexRoot);

FOUNDATION_EXPORT void OrgLukhnosLucenestudySuggester_rebuildWithNSString_(NSString *indexRoot);

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudySuggester)

#endif // _OrgLukhnosLucenestudySuggester_H_
