//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Suggester.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgLukhnosLucenestudySuggester")
#ifdef RESTRICT_OrgLukhnosLucenestudySuggester
#define INCLUDE_ALL_OrgLukhnosLucenestudySuggester 0
#else
#define INCLUDE_ALL_OrgLukhnosLucenestudySuggester 1
#endif
#undef RESTRICT_OrgLukhnosLucenestudySuggester

#if !defined (OrgLukhnosLucenestudySuggester_) && (INCLUDE_ALL_OrgLukhnosLucenestudySuggester || defined(INCLUDE_OrgLukhnosLucenestudySuggester))
#define OrgLukhnosLucenestudySuggester_

#define RESTRICT_JavaLangAutoCloseable 1
#define INCLUDE_JavaLangAutoCloseable 1
#include "java/lang/AutoCloseable.h"

@class OrgApacheLuceneSearchSuggestAnalyzingAnalyzingInfixSuggester;
@class OrgLukhnosPortmobileFilePath;
@protocol JavaUtilList;

@interface OrgLukhnosLucenestudySuggester : NSObject < JavaLangAutoCloseable > {
 @public
  OrgLukhnosPortmobileFilePath *indexRootPath_;
  OrgApacheLuceneSearchSuggestAnalyzingAnalyzingInfixSuggester *suggester_;
  jint suggestionCount_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)indexRoot;

- (void)close;

+ (void)rebuildWithNSString:(NSString *)indexRoot;

- (id<JavaUtilList>)suggestWithNSString:(NSString *)query;

#pragma mark Package-Private

+ (OrgLukhnosPortmobileFilePath *)getSuggestionIndexPathWithOrgLukhnosPortmobileFilePath:(OrgLukhnosPortmobileFilePath *)indexRoot;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudySuggester)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySuggester, indexRootPath_, OrgLukhnosPortmobileFilePath *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySuggester, suggester_, OrgApacheLuceneSearchSuggestAnalyzingAnalyzingInfixSuggester *)

inline jint OrgLukhnosLucenestudySuggester_get_DEFAULT_SUGGESTION_COUNT(void);
#define OrgLukhnosLucenestudySuggester_DEFAULT_SUGGESTION_COUNT 10
J2OBJC_STATIC_FIELD_CONSTANT(OrgLukhnosLucenestudySuggester, DEFAULT_SUGGESTION_COUNT, jint)

inline NSString *OrgLukhnosLucenestudySuggester_get_INDEX_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgLukhnosLucenestudySuggester_INDEX_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgLukhnosLucenestudySuggester, INDEX_NAME, NSString *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudySuggester_initWithNSString_(OrgLukhnosLucenestudySuggester *self, NSString *indexRoot);

FOUNDATION_EXPORT OrgLukhnosLucenestudySuggester *new_OrgLukhnosLucenestudySuggester_initWithNSString_(NSString *indexRoot) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgLukhnosLucenestudySuggester *create_OrgLukhnosLucenestudySuggester_initWithNSString_(NSString *indexRoot);

FOUNDATION_EXPORT OrgLukhnosPortmobileFilePath *OrgLukhnosLucenestudySuggester_getSuggestionIndexPathWithOrgLukhnosPortmobileFilePath_(OrgLukhnosPortmobileFilePath *indexRoot);

FOUNDATION_EXPORT void OrgLukhnosLucenestudySuggester_rebuildWithNSString_(NSString *indexRoot);

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudySuggester)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgLukhnosLucenestudySuggester")
