//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Util.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgLukhnosLucenestudyUtil")
#ifdef RESTRICT_OrgLukhnosLucenestudyUtil
#define INCLUDE_ALL_OrgLukhnosLucenestudyUtil 0
#else
#define INCLUDE_ALL_OrgLukhnosLucenestudyUtil 1
#endif
#undef RESTRICT_OrgLukhnosLucenestudyUtil

#if !defined (OrgLukhnosLucenestudyUtil_) && (INCLUDE_ALL_OrgLukhnosLucenestudyUtil || defined(INCLUDE_OrgLukhnosLucenestudyUtil))
#define OrgLukhnosLucenestudyUtil_

@class OrgLukhnosPortmobileFilePath;

@interface OrgLukhnosLucenestudyUtil : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)deletePathWithOrgLukhnosPortmobileFilePath:(OrgLukhnosPortmobileFilePath *)path;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudyUtil)

FOUNDATION_EXPORT void OrgLukhnosLucenestudyUtil_deletePathWithOrgLukhnosPortmobileFilePath_(OrgLukhnosPortmobileFilePath *path);

FOUNDATION_EXPORT void OrgLukhnosLucenestudyUtil_init(OrgLukhnosLucenestudyUtil *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudyUtil *new_OrgLukhnosLucenestudyUtil_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgLukhnosLucenestudyUtil *create_OrgLukhnosLucenestudyUtil_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyUtil)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgLukhnosLucenestudyUtil")
