//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Util.java
//

#include "J2ObjC_source.h"
#include "java/io/IOException.h"
#include "org/lukhnos/lucenestudy/Util.h"
#include "org/lukhnos/portmobile/file/FileVisitResult.h"
#include "org/lukhnos/portmobile/file/Files.h"
#include "org/lukhnos/portmobile/file/Path.h"
#include "org/lukhnos/portmobile/file/SimpleFileVisitor.h"
#include "org/lukhnos/portmobile/file/attribute/BasicFileAttributes.h"

#if !__has_feature(objc_arc)
#error "org/lukhnos/lucenestudy/Util must be compiled with ARC (-fobjc-arc)"
#endif

@interface OrgLukhnosLucenestudyUtil_1 : OrgLukhnosPortmobileFileSimpleFileVisitor

- (instancetype)init;

- (OrgLukhnosPortmobileFileFileVisitResult *)visitFileWithId:(OrgLukhnosPortmobileFilePath *)file
    withOrgLukhnosPortmobileFileAttributeBasicFileAttributes:(OrgLukhnosPortmobileFileAttributeBasicFileAttributes *)attrs;

- (OrgLukhnosPortmobileFileFileVisitResult *)postVisitDirectoryWithId:(OrgLukhnosPortmobileFilePath *)dir
                                                withJavaIoIOException:(JavaIoIOException *)exc;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudyUtil_1)

__attribute__((unused)) static void OrgLukhnosLucenestudyUtil_1_init(OrgLukhnosLucenestudyUtil_1 *self);

__attribute__((unused)) static OrgLukhnosLucenestudyUtil_1 *new_OrgLukhnosLucenestudyUtil_1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgLukhnosLucenestudyUtil_1 *create_OrgLukhnosLucenestudyUtil_1_init(void);

@implementation OrgLukhnosLucenestudyUtil

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgLukhnosLucenestudyUtil_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)deletePathWithOrgLukhnosPortmobileFilePath:(OrgLukhnosPortmobileFilePath *)path {
  OrgLukhnosLucenestudyUtil_deletePathWithOrgLukhnosPortmobileFilePath_(path);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 0, 1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(deletePathWithOrgLukhnosPortmobileFilePath:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "deletePath", "LOrgLukhnosPortmobileFilePath;", "LJavaIoIOException;" };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudyUtil = { "Util", "org.lukhnos.lucenestudy", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_OrgLukhnosLucenestudyUtil;
}

@end

void OrgLukhnosLucenestudyUtil_init(OrgLukhnosLucenestudyUtil *self) {
  NSObject_init(self);
}

OrgLukhnosLucenestudyUtil *new_OrgLukhnosLucenestudyUtil_init() {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudyUtil, init)
}

OrgLukhnosLucenestudyUtil *create_OrgLukhnosLucenestudyUtil_init() {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudyUtil, init)
}

void OrgLukhnosLucenestudyUtil_deletePathWithOrgLukhnosPortmobileFilePath_(OrgLukhnosPortmobileFilePath *path) {
  OrgLukhnosLucenestudyUtil_initialize();
  (void) OrgLukhnosPortmobileFileFiles_walkFileTreeWithOrgLukhnosPortmobileFilePath_withOrgLukhnosPortmobileFileFileVisitor_(path, new_OrgLukhnosLucenestudyUtil_1_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudyUtil)

@implementation OrgLukhnosLucenestudyUtil_1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgLukhnosLucenestudyUtil_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (OrgLukhnosPortmobileFileFileVisitResult *)visitFileWithId:(OrgLukhnosPortmobileFilePath *)file
    withOrgLukhnosPortmobileFileAttributeBasicFileAttributes:(OrgLukhnosPortmobileFileAttributeBasicFileAttributes *)attrs {
  OrgLukhnosPortmobileFileFiles_delete__WithOrgLukhnosPortmobileFilePath_(file);
  return JreRetainedLocalValue(JreLoadEnum(OrgLukhnosPortmobileFileFileVisitResult, CONTINUE));
}

- (OrgLukhnosPortmobileFileFileVisitResult *)postVisitDirectoryWithId:(OrgLukhnosPortmobileFilePath *)dir
                                                withJavaIoIOException:(JavaIoIOException *)exc {
  OrgLukhnosPortmobileFileFiles_delete__WithOrgLukhnosPortmobileFilePath_(dir);
  return JreRetainedLocalValue(JreLoadEnum(OrgLukhnosPortmobileFileFileVisitResult, CONTINUE));
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgLukhnosPortmobileFileFileVisitResult;", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "LOrgLukhnosPortmobileFileFileVisitResult;", 0x1, 3, 4, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(visitFileWithId:withOrgLukhnosPortmobileFileAttributeBasicFileAttributes:);
  methods[2].selector = @selector(postVisitDirectoryWithId:withJavaIoIOException:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "visitFile", "LOrgLukhnosPortmobileFilePath;LOrgLukhnosPortmobileFileAttributeBasicFileAttributes;", "LJavaIoIOException;", "postVisitDirectory", "LOrgLukhnosPortmobileFilePath;LJavaIoIOException;", "LOrgLukhnosLucenestudyUtil;", "deletePathWithOrgLukhnosPortmobileFilePath:", "Lorg/lukhnos/portmobile/file/SimpleFileVisitor<Lorg/lukhnos/portmobile/file/Path;>;" };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudyUtil_1 = { "", "org.lukhnos.lucenestudy", ptrTable, methods, NULL, 7, 0x8018, 3, 0, 5, -1, 6, 7, -1 };
  return &_OrgLukhnosLucenestudyUtil_1;
}

@end

void OrgLukhnosLucenestudyUtil_1_init(OrgLukhnosLucenestudyUtil_1 *self) {
  OrgLukhnosPortmobileFileSimpleFileVisitor_init(self);
}

OrgLukhnosLucenestudyUtil_1 *new_OrgLukhnosLucenestudyUtil_1_init() {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudyUtil_1, init)
}

OrgLukhnosLucenestudyUtil_1 *create_OrgLukhnosLucenestudyUtil_1_init() {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudyUtil_1, init)
}
