//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/lukhnos/lucenestudy/Util.java
//

#ifndef _OrgLukhnosLucenestudyUtil_H_
#define _OrgLukhnosLucenestudyUtil_H_

#include "J2ObjC_header.h"

@class OrgLukhnosPortmobileFilePath;

@interface OrgLukhnosLucenestudyUtil : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)deletePathWithOrgLukhnosPortmobileFilePath:(OrgLukhnosPortmobileFilePath *)path;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudyUtil)

FOUNDATION_EXPORT void OrgLukhnosLucenestudyUtil_deletePathWithOrgLukhnosPortmobileFilePath_(OrgLukhnosPortmobileFilePath *path);

FOUNDATION_EXPORT void OrgLukhnosLucenestudyUtil_init(OrgLukhnosLucenestudyUtil *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudyUtil *new_OrgLukhnosLucenestudyUtil_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyUtil)

#endif // _OrgLukhnosLucenestudyUtil_H_
