//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/test/java/org/lukhnos/lucenestudy/AppendDocumentTest.java
//

#ifndef _OrgLukhnosLucenestudyAppendDocumentTest_H_
#define _OrgLukhnosLucenestudyAppendDocumentTest_H_

#include "J2ObjC_header.h"

@class OrgLukhnosLucenestudySearcher;
@class OrgLukhnosPortmobileFilePath;

@interface OrgLukhnosLucenestudyAppendDocumentTest : NSObject {
 @public
  OrgLukhnosPortmobileFilePath *temp_;
  OrgLukhnosLucenestudySearcher *searcher_;
}

#pragma mark Public

- (instancetype)init;

- (void)appendDocumentTest;

- (void)setUp;

- (void)tearDown;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudyAppendDocumentTest)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyAppendDocumentTest, temp_, OrgLukhnosPortmobileFilePath *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyAppendDocumentTest, searcher_, OrgLukhnosLucenestudySearcher *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudyAppendDocumentTest_init(OrgLukhnosLucenestudyAppendDocumentTest *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudyAppendDocumentTest *new_OrgLukhnosLucenestudyAppendDocumentTest_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyAppendDocumentTest)

#endif // _OrgLukhnosLucenestudyAppendDocumentTest_H_
