//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/test/java/org/lukhnos/lucenestudy/AppendDocumentTest.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Exception.h"
#include "java/util/Arrays.h"
#include "java/util/List.h"
#include "org/junit/After.h"
#include "org/junit/Assert.h"
#include "org/junit/Before.h"
#include "org/junit/Test.h"
#include "org/lukhnos/lucenestudy/AppendDocumentTest.h"
#include "org/lukhnos/lucenestudy/Document.h"
#include "org/lukhnos/lucenestudy/Indexer.h"
#include "org/lukhnos/lucenestudy/SearchResult.h"
#include "org/lukhnos/lucenestudy/Searcher.h"
#include "org/lukhnos/lucenestudy/SuggesterTest.h"
#include "org/lukhnos/lucenestudy/Util.h"
#include "org/lukhnos/portmobile/file/Files.h"
#include "org/lukhnos/portmobile/file/Path.h"

@implementation OrgLukhnosLucenestudyAppendDocumentTest

- (void)setUp {
  JreStrongAssign(&temp_, OrgLukhnosPortmobileFileFiles_createTempDirectoryWithNSString_([OrgLukhnosLucenestudySuggesterTest_class_() getCanonicalName]));
}

- (void)tearDown {
  [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) close];
  OrgLukhnosLucenestudyUtil_deletePathWithOrgLukhnosPortmobileFilePath_(temp_);
}

- (void)appendDocumentTest {
  IOSObjectArray *docs1 = [IOSObjectArray arrayWithObjects:(id[]){ [new_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"computer", 2000, 5, NO, @"", @"") autorelease], [new_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"compute", 2000, 2, NO, @"", @"") autorelease] } count:2 type:OrgLukhnosLucenestudyDocument_class_()];
  IOSObjectArray *docs2 = [IOSObjectArray arrayWithObjects:(id[]){ [new_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"computing", 2000, 2, NO, @"", @"") autorelease] } count:1 type:OrgLukhnosLucenestudyDocument_class_()];
  OrgLukhnosLucenestudyIndexer *indexer = [new_OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_([((OrgLukhnosPortmobileFilePath *) nil_chk(temp_)) description], NO) autorelease];
  [indexer addDocumentsWithJavaUtilList:JavaUtilArrays_asListWithNSObjectArray_(docs1)];
  [indexer close];
  JreStrongAssignAndConsume(&searcher_, new_OrgLukhnosLucenestudySearcher_initWithNSString_([temp_ description]));
  OrgLukhnosLucenestudySearchResult *result;
  result = [searcher_ searchWithNSString:@"c*" withInt:10];
  OrgJunitAssert_assertEqualsWithLong_withLong_(docs1->size_, ((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->totalHits_);
  [searcher_ close];
  indexer = [new_OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_([temp_ description], YES) autorelease];
  [indexer addDocumentsWithJavaUtilList:JavaUtilArrays_asListWithNSObjectArray_(docs2)];
  [indexer close];
  JreStrongAssignAndConsume(&searcher_, new_OrgLukhnosLucenestudySearcher_initWithNSString_([temp_ description]));
  result = [searcher_ searchWithNSString:@"c*" withInt:10];
  OrgJunitAssert_assertEqualsWithLong_withLong_(docs1->size_ + docs2->size_, ((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->totalHits_);
  [searcher_ close];
}

- (instancetype)init {
  OrgLukhnosLucenestudyAppendDocumentTest_init(self);
  return self;
}

- (void)dealloc {
  RELEASE_(temp_);
  RELEASE_(searcher_);
  [super dealloc];
}

+ (IOSObjectArray *)__annotations_setUp {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitBefore alloc] init] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_tearDown {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitAfter alloc] init] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_appendDocumentTest {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setUp", NULL, "V", 0x1, "Ljava.lang.Exception;", NULL },
    { "tearDown", NULL, "V", 0x1, "Ljava.lang.Exception;", NULL },
    { "appendDocumentTest", NULL, "V", 0x1, "Ljava.lang.Exception;", NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "temp_", NULL, 0x0, "Lorg.lukhnos.portmobile.file.Path;", NULL, NULL, .constantValue.asLong = 0 },
    { "searcher_", NULL, 0x0, "Lorg.lukhnos.lucenestudy.Searcher;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudyAppendDocumentTest = { 2, "AppendDocumentTest", "org.lukhnos.lucenestudy", NULL, 0x1, 4, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgLukhnosLucenestudyAppendDocumentTest;
}

@end

void OrgLukhnosLucenestudyAppendDocumentTest_init(OrgLukhnosLucenestudyAppendDocumentTest *self) {
  NSObject_init(self);
}

OrgLukhnosLucenestudyAppendDocumentTest *new_OrgLukhnosLucenestudyAppendDocumentTest_init() {
  OrgLukhnosLucenestudyAppendDocumentTest *self = [OrgLukhnosLucenestudyAppendDocumentTest alloc];
  OrgLukhnosLucenestudyAppendDocumentTest_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudyAppendDocumentTest)
