//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/test/java/org/lukhnos/lucenestudy/IndexerTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgLukhnosLucenestudyIndexerTest")
#ifdef RESTRICT_OrgLukhnosLucenestudyIndexerTest
#define INCLUDE_ALL_OrgLukhnosLucenestudyIndexerTest 0
#else
#define INCLUDE_ALL_OrgLukhnosLucenestudyIndexerTest 1
#endif
#undef RESTRICT_OrgLukhnosLucenestudyIndexerTest

#if !defined (OrgLukhnosLucenestudyIndexerTest_) && (INCLUDE_ALL_OrgLukhnosLucenestudyIndexerTest || defined(INCLUDE_OrgLukhnosLucenestudyIndexerTest))
#define OrgLukhnosLucenestudyIndexerTest_

@class OrgLukhnosLucenestudySearcher;
@class OrgLukhnosPortmobileFilePath;

@interface OrgLukhnosLucenestudyIndexerTest : NSObject {
 @public
  OrgLukhnosPortmobileFilePath *temp_;
  OrgLukhnosLucenestudySearcher *searcher_;
}

#pragma mark Public

- (instancetype)init;

- (void)appendDocumentTest;

- (void)deleteDocumentTest;

- (void)setUp;

- (void)tearDown;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudyIndexerTest)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyIndexerTest, temp_, OrgLukhnosPortmobileFilePath *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudyIndexerTest, searcher_, OrgLukhnosLucenestudySearcher *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudyIndexerTest_init(OrgLukhnosLucenestudyIndexerTest *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudyIndexerTest *new_OrgLukhnosLucenestudyIndexerTest_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgLukhnosLucenestudyIndexerTest *create_OrgLukhnosLucenestudyIndexerTest_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudyIndexerTest)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgLukhnosLucenestudyIndexerTest")
