//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/test/java/org/lukhnos/lucenestudy/SearcherTest.java
//

#ifndef _OrgLukhnosLucenestudySearcherTest_H_
#define _OrgLukhnosLucenestudySearcherTest_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;
@class OrgLukhnosLucenestudySearcher;
@class OrgLukhnosPortmobileFilePath;

@interface OrgLukhnosLucenestudySearcherTest : NSObject {
 @public
  OrgLukhnosPortmobileFilePath *temp_;
  OrgLukhnosLucenestudySearcher *searcher_;
  IOSObjectArray *docs_;
}

#pragma mark Public

- (instancetype)init;

- (void)basicTest;

- (void)highlightingTest;

- (void)pagingTest;

- (void)setUp;

- (void)sortAndPagingTest;

- (void)sortTest;

- (void)tearDown;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudySearcherTest)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearcherTest, temp_, OrgLukhnosPortmobileFilePath *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearcherTest, searcher_, OrgLukhnosLucenestudySearcher *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearcherTest, docs_, IOSObjectArray *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudySearcherTest_init(OrgLukhnosLucenestudySearcherTest *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudySearcherTest *new_OrgLukhnosLucenestudySearcherTest_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudySearcherTest)

#endif // _OrgLukhnosLucenestudySearcherTest_H_
