//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/test/java/org/lukhnos/lucenestudy/SearcherTest.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/io/IOException.h"
#include "java/lang/Exception.h"
#include "java/lang/annotation/Annotation.h"
#include "java/util/Arrays.h"
#include "java/util/List.h"
#include "org/apache/lucene/queryparser/classic/ParseException.h"
#include "org/junit/After.h"
#include "org/junit/Assert.h"
#include "org/junit/Before.h"
#include "org/junit/Test.h"
#include "org/lukhnos/lucenestudy/Document.h"
#include "org/lukhnos/lucenestudy/Indexer.h"
#include "org/lukhnos/lucenestudy/SearchResult.h"
#include "org/lukhnos/lucenestudy/Searcher.h"
#include "org/lukhnos/lucenestudy/SearcherTest.h"
#include "org/lukhnos/lucenestudy/SuggesterTest.h"
#include "org/lukhnos/lucenestudy/Util.h"
#include "org/lukhnos/portmobile/file/Files.h"
#include "org/lukhnos/portmobile/file/Path.h"

@implementation OrgLukhnosLucenestudySearcherTest

- (void)setUp {
  temp_ = OrgLukhnosPortmobileFileFiles_createTempDirectoryWithNSString_([OrgLukhnosLucenestudySuggesterTest_class_() getCanonicalName]);
  OrgLukhnosLucenestudyIndexer *indexer = new_OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_([((OrgLukhnosPortmobileFilePath *) nil_chk(temp_)) description], false);
  [indexer addDocumentsWithJavaUtilList:JavaUtilArrays_asListWithNSObjectArray_(docs_)];
  [indexer close];
  searcher_ = new_OrgLukhnosLucenestudySearcher_initWithNSString_([((OrgLukhnosPortmobileFilePath *) nil_chk(temp_)) description]);
}

- (void)tearDown {
  [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) close];
  OrgLukhnosLucenestudyUtil_deletePathWithOrgLukhnosPortmobileFilePath_(temp_);
}

- (void)basicTest {
  OrgLukhnosLucenestudySearchResult *result;
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"t*" withInt:10];
  OrgJunitAssert_assertEqualsWithLong_withLong_(((IOSObjectArray *) nil_chk(docs_))->size_, ((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->totalHits_);
  OrgJunitAssert_assertEqualsWithLong_withLong_(((IOSObjectArray *) nil_chk(docs_))->size_, [((id<JavaUtilList>) nil_chk(result->documents_)) size]);
}

- (void)pagingTest {
  OrgLukhnosLucenestudySearchResult *result;
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"t*" withInt:((IOSObjectArray *) nil_chk(docs_))->size_];
  OrgJunitAssert_assertEqualsWithLong_withLong_(((IOSObjectArray *) nil_chk(docs_))->size_, ((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->totalHits_);
  OrgJunitAssert_assertEqualsWithLong_withLong_(((IOSObjectArray *) nil_chk(docs_))->size_, [((id<JavaUtilList>) nil_chk(result->documents_)) size]);
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"t*" withInt:3];
  OrgJunitAssert_assertEqualsWithLong_withLong_(((IOSObjectArray *) nil_chk(docs_))->size_, ((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->totalHits_);
  OrgJunitAssert_assertEqualsWithLong_withLong_(3, [result->documents_ size]);
  OrgJunitAssert_assertTrueWithBoolean_([result hasMore]);
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchAfterWithOrgLukhnosLucenestudySearchResult:result withInt:3];
  OrgJunitAssert_assertEqualsWithLong_withLong_(((IOSObjectArray *) nil_chk(docs_))->size_, ((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->totalHits_);
  OrgJunitAssert_assertEqualsWithLong_withLong_(2, [result->documents_ size]);
  OrgJunitAssert_assertFalseWithBoolean_([result hasMore]);
}

- (void)sortTest {
  OrgLukhnosLucenestudySearchResult *result;
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"t*" withOrgLukhnosLucenestudySearcher_SortBy:JreLoadEnum(OrgLukhnosLucenestudySearcher_SortBy, TITLE) withInt:5];
  OrgJunitAssert_assertEqualsWithId_withId_(@"Test", ((OrgLukhnosLucenestudyDocument *) nil_chk([((id<JavaUtilList>) nil_chk(((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->documents_)) getWithInt:0]))->title_);
  OrgJunitAssert_assertEqualsWithId_withId_(@"Testing", ((OrgLukhnosLucenestudyDocument *) nil_chk([result->documents_ getWithInt:4]))->title_);
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"t*" withOrgLukhnosLucenestudySearcher_SortBy:JreLoadEnum(OrgLukhnosLucenestudySearcher_SortBy, RELEVANCE) withInt:5];
  OrgJunitAssert_assertEqualsWithId_withId_(@"Test", ((OrgLukhnosLucenestudyDocument *) nil_chk([((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->documents_ getWithInt:0]))->title_);
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"t*" withOrgLukhnosLucenestudySearcher_SortBy:JreLoadEnum(OrgLukhnosLucenestudySearcher_SortBy, DOCUMENT_ORDER) withInt:2];
  OrgJunitAssert_assertEqualsWithId_withId_(@"Testing", ((OrgLukhnosLucenestudyDocument *) nil_chk([((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->documents_ getWithInt:1]))->title_);
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"t*" withOrgLukhnosLucenestudySearcher_SortBy:JreLoadEnum(OrgLukhnosLucenestudySearcher_SortBy, YEAR) withInt:5];
  OrgJunitAssert_assertEqualsWithLong_withLong_(2000, ((OrgLukhnosLucenestudyDocument *) nil_chk([((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->documents_ getWithInt:0]))->year_);
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"t*" withOrgLukhnosLucenestudySearcher_SortBy:JreLoadEnum(OrgLukhnosLucenestudySearcher_SortBy, RATING) withInt:3];
  OrgJunitAssert_assertEqualsWithLong_withLong_(((IOSObjectArray *) nil_chk(docs_))->size_, ((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->totalHits_);
  OrgJunitAssert_assertEqualsWithLong_withLong_(3, [result->documents_ size]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"Testcase", ((OrgLukhnosLucenestudyDocument *) nil_chk([result->documents_ getWithInt:0]))->title_);
  OrgJunitAssert_assertTrueWithBoolean_([result hasMore]);
}

- (void)sortAndPagingTest {
  OrgLukhnosLucenestudySearchResult *result;
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"t*" withOrgLukhnosLucenestudySearcher_SortBy:JreLoadEnum(OrgLukhnosLucenestudySearcher_SortBy, RATING) withInt:3];
  OrgJunitAssert_assertEqualsWithLong_withLong_(((IOSObjectArray *) nil_chk(docs_))->size_, ((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->totalHits_);
  OrgJunitAssert_assertEqualsWithLong_withLong_(3, [((id<JavaUtilList>) nil_chk(result->documents_)) size]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"Testcase", ((OrgLukhnosLucenestudyDocument *) nil_chk([result->documents_ getWithInt:0]))->title_);
  OrgJunitAssert_assertTrueWithBoolean_([result hasMore]);
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchAfterWithOrgLukhnosLucenestudySearchResult:result withInt:2];
  OrgJunitAssert_assertEqualsWithLong_withLong_(((IOSObjectArray *) nil_chk(docs_))->size_, ((OrgLukhnosLucenestudySearchResult *) nil_chk(result))->totalHits_);
  OrgJunitAssert_assertEqualsWithLong_withLong_(2, [result->documents_ size]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"Testing", ((OrgLukhnosLucenestudyDocument *) nil_chk([result->documents_ getWithInt:0]))->title_);
  OrgJunitAssert_assertFalseWithBoolean_([result hasMore]);
}

- (void)highlightingTest {
  OrgLukhnosLucenestudySearchResult *result;
  result = [((OrgLukhnosLucenestudySearcher *) nil_chk(searcher_)) searchWithNSString:@"test" withOrgLukhnosLucenestudySearcher_SortBy:JreLoadEnum(OrgLukhnosLucenestudySearcher_SortBy, DOCUMENT_ORDER) withInt:5];
  OrgJunitAssert_assertEqualsWithId_withId_(@"<B>Test</B>", [((OrgLukhnosLucenestudySearchResult *) nil_chk(result)) getHighlightedTitleWithOrgLukhnosLucenestudyDocument:[((id<JavaUtilList>) nil_chk(result->documents_)) getWithInt:0]]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"It's important to <B>test</B> &amp; fix", [result getHighlightedReviewWithOrgLukhnosLucenestudyDocument:[result->documents_ getWithInt:0]]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgLukhnosLucenestudySearcherTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (IOSObjectArray *)__annotations_setUp {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitBefore() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_tearDown {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitAfter() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_basicTest {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0LL) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_pagingTest {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0LL) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sortTest {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0LL) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sortAndPagingTest {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0LL) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_highlightingTest {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0LL) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setUp", NULL, "V", 0x1, "Ljava.lang.Exception;", NULL },
    { "tearDown", NULL, "V", 0x1, "Ljava.lang.Exception;", NULL },
    { "basicTest", NULL, "V", 0x1, "Ljava.lang.Exception;", NULL },
    { "pagingTest", NULL, "V", 0x1, "Ljava.io.IOException;Lorg.apache.lucene.queryparser.classic.ParseException;", NULL },
    { "sortTest", NULL, "V", 0x1, "Ljava.lang.Exception;", NULL },
    { "sortAndPagingTest", NULL, "V", 0x1, "Ljava.io.IOException;Lorg.apache.lucene.queryparser.classic.ParseException;", NULL },
    { "highlightingTest", NULL, "V", 0x1, "Ljava.lang.Exception;", NULL },
    { "init", "SearcherTest", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "temp_", NULL, 0x0, "Lorg.lukhnos.portmobile.file.Path;", NULL, NULL, .constantValue.asLong = 0 },
    { "searcher_", NULL, 0x0, "Lorg.lukhnos.lucenestudy.Searcher;", NULL, NULL, .constantValue.asLong = 0 },
    { "docs_", NULL, 0x0, "[Lorg.lukhnos.lucenestudy.Document;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudySearcherTest = { 2, "SearcherTest", "org.lukhnos.lucenestudy", NULL, 0x1, 8, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgLukhnosLucenestudySearcherTest;
}

@end

void OrgLukhnosLucenestudySearcherTest_init(OrgLukhnosLucenestudySearcherTest *self) {
  NSObject_init(self);
  self->docs_ = [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"Test", 2000, 5, false, @"It's important to test & fix", @""), create_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"Testing", 2000, 2, false, @"", @""), create_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"Tested", 1999, 6, false, @"", @""), create_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"Tester", 1984, 0, false, @"", @""), create_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"Testcase", 1970, 10, false, @"It's all about testing and testers.", @"") } count:5 type:OrgLukhnosLucenestudyDocument_class_()];
}

OrgLukhnosLucenestudySearcherTest *new_OrgLukhnosLucenestudySearcherTest_init() {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudySearcherTest, init)
}

OrgLukhnosLucenestudySearcherTest *create_OrgLukhnosLucenestudySearcherTest_init() {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudySearcherTest, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudySearcherTest)
