//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/test/java/org/lukhnos/lucenestudy/SearcherTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgLukhnosLucenestudySearcherTest")
#ifdef RESTRICT_OrgLukhnosLucenestudySearcherTest
#define INCLUDE_ALL_OrgLukhnosLucenestudySearcherTest 0
#else
#define INCLUDE_ALL_OrgLukhnosLucenestudySearcherTest 1
#endif
#undef RESTRICT_OrgLukhnosLucenestudySearcherTest

#if !defined (OrgLukhnosLucenestudySearcherTest_) && (INCLUDE_ALL_OrgLukhnosLucenestudySearcherTest || defined(INCLUDE_OrgLukhnosLucenestudySearcherTest))
#define OrgLukhnosLucenestudySearcherTest_

@class IOSObjectArray;
@class OrgLukhnosLucenestudySearcher;
@class OrgLukhnosPortmobileFilePath;

@interface OrgLukhnosLucenestudySearcherTest : NSObject {
 @public
  OrgLukhnosPortmobileFilePath *temp_;
  OrgLukhnosLucenestudySearcher *searcher_;
  IOSObjectArray *docs_;
}

#pragma mark Public

- (instancetype)init;

- (void)basicTest;

- (void)highlightingTest;

- (void)pagingTest;

- (void)setUp;

- (void)sortAndPagingTest;

- (void)sortTest;

- (void)tearDown;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudySearcherTest)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearcherTest, temp_, OrgLukhnosPortmobileFilePath *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearcherTest, searcher_, OrgLukhnosLucenestudySearcher *)
J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySearcherTest, docs_, IOSObjectArray *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudySearcherTest_init(OrgLukhnosLucenestudySearcherTest *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudySearcherTest *new_OrgLukhnosLucenestudySearcherTest_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgLukhnosLucenestudySearcherTest *create_OrgLukhnosLucenestudySearcherTest_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudySearcherTest)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgLukhnosLucenestudySearcherTest")
