//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/test/java/org/lukhnos/lucenestudy/SuggesterTest.java
//

#ifndef _OrgLukhnosLucenestudySuggesterTest_H_
#define _OrgLukhnosLucenestudySuggesterTest_H_

#include "J2ObjC_header.h"

@class OrgLukhnosPortmobileFilePath;

@interface OrgLukhnosLucenestudySuggesterTest : NSObject {
 @public
  OrgLukhnosPortmobileFilePath *temp_;
}

#pragma mark Public

- (instancetype)init;

- (void)basicTest;

- (void)setUp;

- (void)tearDown;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudySuggesterTest)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySuggesterTest, temp_, OrgLukhnosPortmobileFilePath *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudySuggesterTest_init(OrgLukhnosLucenestudySuggesterTest *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudySuggesterTest *new_OrgLukhnosLucenestudySuggesterTest_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudySuggesterTest)

#endif // _OrgLukhnosLucenestudySuggesterTest_H_
