//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/test/java/org/lukhnos/lucenestudy/SuggesterTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgLukhnosLucenestudySuggesterTest")
#ifdef RESTRICT_OrgLukhnosLucenestudySuggesterTest
#define INCLUDE_ALL_OrgLukhnosLucenestudySuggesterTest 0
#else
#define INCLUDE_ALL_OrgLukhnosLucenestudySuggesterTest 1
#endif
#undef RESTRICT_OrgLukhnosLucenestudySuggesterTest

#if !defined (OrgLukhnosLucenestudySuggesterTest_) && (INCLUDE_ALL_OrgLukhnosLucenestudySuggesterTest || defined(INCLUDE_OrgLukhnosLucenestudySuggesterTest))
#define OrgLukhnosLucenestudySuggesterTest_

@class IOSObjectArray;
@class OrgLukhnosPortmobileFilePath;

@interface OrgLukhnosLucenestudySuggesterTest : NSObject {
 @public
  OrgLukhnosPortmobileFilePath *temp_;
}

#pragma mark Public

- (instancetype)init;

- (void)basicTest;

- (void)setUp;

- (void)tearDown;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgLukhnosLucenestudySuggesterTest)

J2OBJC_FIELD_SETTER(OrgLukhnosLucenestudySuggesterTest, temp_, OrgLukhnosPortmobileFilePath *)

FOUNDATION_EXPORT void OrgLukhnosLucenestudySuggesterTest_init(OrgLukhnosLucenestudySuggesterTest *self);

FOUNDATION_EXPORT OrgLukhnosLucenestudySuggesterTest *new_OrgLukhnosLucenestudySuggesterTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgLukhnosLucenestudySuggesterTest *create_OrgLukhnosLucenestudySuggesterTest_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgLukhnosLucenestudySuggesterTest)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgLukhnosLucenestudySuggesterTest")
