//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/test/java/org/lukhnos/lucenestudy/SuggesterTest.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/io/PrintStream.h"
#include "java/lang/System.h"
#include "java/lang/annotation/Annotation.h"
#include "java/util/Arrays.h"
#include "java/util/List.h"
#include "org/junit/After.h"
#include "org/junit/Before.h"
#include "org/junit/Test.h"
#include "org/lukhnos/lucenestudy/Document.h"
#include "org/lukhnos/lucenestudy/Indexer.h"
#include "org/lukhnos/lucenestudy/Suggester.h"
#include "org/lukhnos/lucenestudy/SuggesterTest.h"
#include "org/lukhnos/lucenestudy/Util.h"
#include "org/lukhnos/portmobile/file/Files.h"
#include "org/lukhnos/portmobile/file/Path.h"

#if !__has_feature(objc_arc)
#error "org/lukhnos/lucenestudy/SuggesterTest must be compiled with ARC (-fobjc-arc)"
#endif

__attribute__((unused)) static IOSObjectArray *OrgLukhnosLucenestudySuggesterTest__Annotations$0(void);

__attribute__((unused)) static IOSObjectArray *OrgLukhnosLucenestudySuggesterTest__Annotations$1(void);

__attribute__((unused)) static IOSObjectArray *OrgLukhnosLucenestudySuggesterTest__Annotations$2(void);

@implementation OrgLukhnosLucenestudySuggesterTest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgLukhnosLucenestudySuggesterTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)setUp {
  temp_ = OrgLukhnosPortmobileFileFiles_createTempDirectoryWithNSString_([OrgLukhnosLucenestudySuggesterTest_class_() getCanonicalName]);
}

- (void)tearDown {
  OrgLukhnosLucenestudyUtil_deletePathWithOrgLukhnosPortmobileFilePath_(temp_);
}

- (void)basicTest {
  OrgLukhnosLucenestudyIndexer *indexer = new_OrgLukhnosLucenestudyIndexer_initWithNSString_([((OrgLukhnosPortmobileFilePath *) nil_chk(temp_)) description]);
  IOSObjectArray *docs = [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"test", 2000, 5, false, @"", @""), create_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"testing", 2000, 0, false, @"", @""), create_OrgLukhnosLucenestudyDocument_initWithNSString_withInt_withInt_withBoolean_withNSString_withNSString_(@"tested", 2000, 0, false, @"", @"") } count:3 type:OrgLukhnosLucenestudyDocument_class_()];
  [indexer addDocumentsWithJavaUtilList:JavaUtilArrays_asListWithNSObjectArray_(docs)];
  [indexer close];
  OrgLukhnosLucenestudySuggester_rebuildWithNSString_([((OrgLukhnosPortmobileFilePath *) nil_chk(temp_)) description]);
  OrgLukhnosLucenestudySuggester *suggester = new_OrgLukhnosLucenestudySuggester_initWithNSString_([((OrgLukhnosPortmobileFilePath *) nil_chk(temp_)) description]);
  id<JavaUtilList> results = [suggester suggestWithNSString:@"tes"];
  [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithId:results];
  [suggester close];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, 1, -1 },
    { NULL, "V", 0x1, -1, -1, 0, -1, 2, -1 },
    { NULL, "V", 0x1, -1, -1, 3, -1, 4, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(setUp);
  methods[2].selector = @selector(tearDown);
  methods[3].selector = @selector(basicTest);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "temp_", "LOrgLukhnosPortmobileFilePath;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaIoIOException;", (void *)&OrgLukhnosLucenestudySuggesterTest__Annotations$0, (void *)&OrgLukhnosLucenestudySuggesterTest__Annotations$1, "LJavaLangException;", (void *)&OrgLukhnosLucenestudySuggesterTest__Annotations$2 };
  static const J2ObjcClassInfo _OrgLukhnosLucenestudySuggesterTest = { "SuggesterTest", "org.lukhnos.lucenestudy", ptrTable, methods, fields, 7, 0x1, 4, 1, -1, -1, -1, -1, -1 };
  return &_OrgLukhnosLucenestudySuggesterTest;
}

@end

void OrgLukhnosLucenestudySuggesterTest_init(OrgLukhnosLucenestudySuggesterTest *self) {
  NSObject_init(self);
}

OrgLukhnosLucenestudySuggesterTest *new_OrgLukhnosLucenestudySuggesterTest_init() {
  J2OBJC_NEW_IMPL(OrgLukhnosLucenestudySuggesterTest, init)
}

OrgLukhnosLucenestudySuggesterTest *create_OrgLukhnosLucenestudySuggesterTest_init() {
  J2OBJC_CREATE_IMPL(OrgLukhnosLucenestudySuggesterTest, init)
}

IOSObjectArray *OrgLukhnosLucenestudySuggesterTest__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitBefore() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *OrgLukhnosLucenestudySuggesterTest__Annotations$1() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitAfter() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *OrgLukhnosLucenestudySuggesterTest__Annotations$2() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0LL) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgLukhnosLucenestudySuggesterTest)
